package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicBlacklist;
import com.asiainfo.aigov.model.healthcare.doctor.PublicBlacklistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicBlacklistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int countByExample(PublicBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int deleteByExample(PublicBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int insert(PublicBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int insertSelective(PublicBlacklist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    List<PublicBlacklist> selectByExampleWithRowbounds(PublicBlacklistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    List<PublicBlacklist> selectByExample(PublicBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicBlacklist record, @Param("example") PublicBlacklistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int updateByExample(@Param("record") PublicBlacklist record, @Param("example") PublicBlacklistExample example);
}