package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorCircle;
import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorCircleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicDoctorCircleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int countByExample(PublicDoctorCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int deleteByExample(PublicDoctorCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int deleteByPrimaryKey(String doctorCircleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int insert(PublicDoctorCircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int insertSelective(PublicDoctorCircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    List<PublicDoctorCircle> selectByExampleWithRowbounds(PublicDoctorCircleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    List<PublicDoctorCircle> selectByExample(PublicDoctorCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    PublicDoctorCircle selectByPrimaryKey(String doctorCircleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicDoctorCircle record, @Param("example") PublicDoctorCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int updateByExample(@Param("record") PublicDoctorCircle record, @Param("example") PublicDoctorCircleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int updateByPrimaryKeySelective(PublicDoctorCircle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE
     *
     * @mbggenerated Thu Apr 20 10:07:25 CST 2017
     */
    int updateByPrimaryKey(PublicDoctorCircle record);
}