package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctor;
import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicDoctorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:50 CST 2017
     */
    int countByExample(PublicDoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int deleteByExample(PublicDoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int deleteByPrimaryKey(String doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int insert(PublicDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int insertSelective(PublicDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    List<PublicDoctor> selectByExampleWithRowbounds(PublicDoctorExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    List<PublicDoctor> selectByExample(PublicDoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    PublicDoctor selectByPrimaryKey(String doctorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicDoctor record, @Param("example") PublicDoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int updateByExample(@Param("record") PublicDoctor record, @Param("example") PublicDoctorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int updateByPrimaryKeySelective(PublicDoctor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR
     *
     * @mbggenerated Wed Apr 26 16:05:51 CST 2017
     */
    int updateByPrimaryKey(PublicDoctor record);
}