package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorScheduleNumber;
import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorScheduleNumberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicDoctorScheduleNumberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int countByExample(PublicDoctorScheduleNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int deleteByExample(PublicDoctorScheduleNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int deleteByPrimaryKey(@Param("hospitalId") String hospitalId, @Param("scheduleId") String scheduleId, @Param("hid") String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int insert(PublicDoctorScheduleNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int insertSelective(PublicDoctorScheduleNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    List<PublicDoctorScheduleNumber> selectByExampleWithRowbounds(PublicDoctorScheduleNumberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    List<PublicDoctorScheduleNumber> selectByExample(PublicDoctorScheduleNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    PublicDoctorScheduleNumber selectByPrimaryKey(@Param("hospitalId") String hospitalId, @Param("scheduleId") String scheduleId, @Param("hid") String hid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicDoctorScheduleNumber record, @Param("example") PublicDoctorScheduleNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int updateByExample(@Param("record") PublicDoctorScheduleNumber record, @Param("example") PublicDoctorScheduleNumberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int updateByPrimaryKeySelective(PublicDoctorScheduleNumber record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE_NUMBER
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    int updateByPrimaryKey(PublicDoctorScheduleNumber record);
}