package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorCircleLike;
import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorCircleLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicDoctorCircleLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int countByExample(PublicDoctorCircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int deleteByExample(PublicDoctorCircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int deleteByPrimaryKey(String likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int insert(PublicDoctorCircleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int insertSelective(PublicDoctorCircleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    List<PublicDoctorCircleLike> selectByExampleWithRowbounds(PublicDoctorCircleLikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    List<PublicDoctorCircleLike> selectByExample(PublicDoctorCircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    PublicDoctorCircleLike selectByPrimaryKey(String likeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicDoctorCircleLike record, @Param("example") PublicDoctorCircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int updateByExample(@Param("record") PublicDoctorCircleLike record, @Param("example") PublicDoctorCircleLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int updateByPrimaryKeySelective(PublicDoctorCircleLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_LIKE
     *
     * @mbggenerated Thu Apr 20 10:49:58 CST 2017
     */
    int updateByPrimaryKey(PublicDoctorCircleLike record);
}