package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorNotice;
import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorNoticeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicDoctorNoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int countByExample(PublicDoctorNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int deleteByExample(PublicDoctorNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int deleteByPrimaryKey(String noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int insert(PublicDoctorNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int insertSelective(PublicDoctorNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    List<PublicDoctorNotice> selectByExampleWithRowbounds(PublicDoctorNoticeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    List<PublicDoctorNotice> selectByExample(PublicDoctorNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    PublicDoctorNotice selectByPrimaryKey(String noticeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicDoctorNotice record, @Param("example") PublicDoctorNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int updateByExample(@Param("record") PublicDoctorNotice record, @Param("example") PublicDoctorNoticeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int updateByPrimaryKeySelective(PublicDoctorNotice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_NOTICE
     *
     * @mbggenerated Thu Apr 20 15:05:29 CST 2017
     */
    int updateByPrimaryKey(PublicDoctorNotice record);
}