package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicHospital;
import com.asiainfo.aigov.model.healthcare.doctor.PublicHospitalExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicHospitalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int countByExample(PublicHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int deleteByExample(PublicHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int insert(PublicHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int insertSelective(PublicHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    List<PublicHospital> selectByExampleWithRowbounds(PublicHospitalExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    List<PublicHospital> selectByExample(PublicHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    PublicHospital selectByPrimaryKey(BigDecimal hospitalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicHospital record, @Param("example") PublicHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int updateByExample(@Param("record") PublicHospital record, @Param("example") PublicHospitalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int updateByPrimaryKeySelective(PublicHospital record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_HOSPITAL
     *
     * @mbggenerated Mon Apr 17 17:58:24 CST 2017
     */
    int updateByPrimaryKey(PublicHospital record);
}