package com.asiainfo.aigov.dao.healthcare.doctor;

import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorCircleVisual;
import com.asiainfo.aigov.model.healthcare.doctor.PublicDoctorCircleVisualExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicDoctorCircleVisualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int countByExample(PublicDoctorCircleVisualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int deleteByExample(PublicDoctorCircleVisualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int deleteByPrimaryKey(String doctorCircleVisualId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int insert(PublicDoctorCircleVisual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int insertSelective(PublicDoctorCircleVisual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    List<PublicDoctorCircleVisual> selectByExampleWithRowbounds(PublicDoctorCircleVisualExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    List<PublicDoctorCircleVisual> selectByExample(PublicDoctorCircleVisualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    PublicDoctorCircleVisual selectByPrimaryKey(String doctorCircleVisualId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicDoctorCircleVisual record, @Param("example") PublicDoctorCircleVisualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int updateByExample(@Param("record") PublicDoctorCircleVisual record, @Param("example") PublicDoctorCircleVisualExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int updateByPrimaryKeySelective(PublicDoctorCircleVisual record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_CIRCLE_VISUAL
     *
     * @mbggenerated Tue Apr 18 21:44:35 CST 2017
     */
    int updateByPrimaryKey(PublicDoctorCircleVisual record);
}