package com.asiainfo.aigov.dao.healthcare.user;

import com.asiainfo.aigov.model.healthcare.user.PublicUser;
import com.asiainfo.aigov.model.healthcare.user.PublicUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int countByExample(PublicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int deleteByExample(PublicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int insert(PublicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int insertSelective(PublicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    List<PublicUser> selectByExampleWithBLOBsWithRowbounds(PublicUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    List<PublicUser> selectByExampleWithBLOBs(PublicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    List<PublicUser> selectByExampleWithRowbounds(PublicUserExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    List<PublicUser> selectByExample(PublicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    PublicUser selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicUser record, @Param("example") PublicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") PublicUser record, @Param("example") PublicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int updateByExample(@Param("record") PublicUser record, @Param("example") PublicUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int updateByPrimaryKeySelective(PublicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(PublicUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER
     *
     * @mbggenerated Tue Apr 18 15:39:04 CST 2017
     */
    int updateByPrimaryKey(PublicUser record);
}