package com.asiainfo.aigov.dao.edot.system;

import com.asiainfo.aigov.model.edot.system.ClientVersion;
import com.asiainfo.aigov.model.edot.system.ClientVersionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

/** 
 * @Title        ClientVersionMapper.java
 * @Description: 客户端版本的持久化层
 * @author:      Administrator
 * @date:        2017年8月3日下午4:37:06 
 *  
 */
public interface ClientVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int countByExample(ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int deleteByExample(ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String osName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int insert(ClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int insertSelective(ClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    List<ClientVersion> selectByExampleWithRowbounds(ClientVersionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    List<ClientVersion> selectByExample(ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    ClientVersion selectByPrimaryKey(String osName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") ClientVersion record, @Param("example") ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int updateByExample(@Param("record") ClientVersion record, @Param("example") ClientVersionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(ClientVersion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CLIENT_VERSION
     *
     * @mbggenerated Fri Jun 24 17:25:31 GMT+08:00 2016
     */
    int updateByPrimaryKey(ClientVersion record);
}