package com.asiainfo.aigov.dao.edot.system;

import com.asiainfo.aigov.model.edot.system.Feature;
import com.asiainfo.aigov.model.edot.system.FeatureExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface FeatureMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int countByExample(FeatureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int deleteByExample(FeatureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int insert(Feature record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int insertSelective(Feature record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	List<Feature> selectByExampleWithRowbounds(FeatureExample example, RowBounds rowBounds);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	List<Feature> selectByExample(FeatureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	Feature selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Feature record, @Param("example") FeatureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int updateByExample(@Param("record") Feature record, @Param("example") FeatureExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int updateByPrimaryKeySelective(Feature record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	int updateByPrimaryKey(Feature record);
}