package com.asiainfo.aigov.dao.edot.system;

import com.asiainfo.aigov.model.edot.system.Region;
import com.asiainfo.aigov.model.edot.system.RegionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

/** 
 * @Title        RegionMapper.java
 * @Description: 注册接口的持久化层
 * @author:      Administrator
 * @date:        2017年8月3日下午4:32:12 
 *  
 */
public interface RegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    int countByExample(RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    int deleteByExample(RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    int insert(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    int insertSelective(Region record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    List<Region> selectByExampleWithRowbounds(RegionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    List<Region> selectByExample(RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    int updateByExampleSelective(@Param("record") Region record, @Param("example") RegionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    int updateByExample(@Param("record") Region record, @Param("example") RegionExample example);
}