package com.asiainfo.aigov.dao.healthcare.guidance;

import com.asiainfo.aigov.model.healthcare.guidance.PublicReplyQuestion;
import com.asiainfo.aigov.model.healthcare.guidance.PublicReplyQuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicReplyQuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int countByExample(PublicReplyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int deleteByExample(PublicReplyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int deleteByPrimaryKey(String replyQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int insert(PublicReplyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int insertSelective(PublicReplyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    List<PublicReplyQuestion> selectByExampleWithRowbounds(PublicReplyQuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    List<PublicReplyQuestion> selectByExample(PublicReplyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    PublicReplyQuestion selectByPrimaryKey(String replyQuestionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicReplyQuestion record, @Param("example") PublicReplyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int updateByExample(@Param("record") PublicReplyQuestion record, @Param("example") PublicReplyQuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int updateByPrimaryKeySelective(PublicReplyQuestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION
     *
     * @mbggenerated Fri Apr 28 17:14:01 CST 2017
     */
    int updateByPrimaryKey(PublicReplyQuestion record);
}