package com.asiainfo.aigov.dao.healthcare.guidance;

import com.asiainfo.aigov.model.healthcare.guidance.PublicReplyQuestionLike;
import com.asiainfo.aigov.model.healthcare.guidance.PublicReplyQuestionLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicReplyQuestionLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int countByExample(PublicReplyQuestionLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int deleteByExample(PublicReplyQuestionLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int deleteByPrimaryKey(@Param("likeMac") String likeMac, @Param("cityVoiceId") String cityVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int insert(PublicReplyQuestionLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int insertSelective(PublicReplyQuestionLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    List<PublicReplyQuestionLike> selectByExampleWithRowbounds(PublicReplyQuestionLikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    List<PublicReplyQuestionLike> selectByExample(PublicReplyQuestionLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    PublicReplyQuestionLike selectByPrimaryKey(@Param("likeMac") String likeMac, @Param("cityVoiceId") String cityVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicReplyQuestionLike record, @Param("example") PublicReplyQuestionLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int updateByExample(@Param("record") PublicReplyQuestionLike record, @Param("example") PublicReplyQuestionLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int updateByPrimaryKeySelective(PublicReplyQuestionLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_REPLY_QUESTION_LIKE
     *
     * @mbggenerated Mon Apr 17 15:18:22 CST 2017
     */
    int updateByPrimaryKey(PublicReplyQuestionLike record);
}