package com.asiainfo.aigov.dao.healthcare.guidance;

import com.asiainfo.aigov.model.healthcare.guidance.ZwzdPartyJibing;
import com.asiainfo.aigov.model.healthcare.guidance.ZwzdPartyJibingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZwzdPartyJibingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int countByExample(ZwzdPartyJibingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int deleteByExample(ZwzdPartyJibingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int insert(ZwzdPartyJibing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int insertSelective(ZwzdPartyJibing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    List<ZwzdPartyJibing> selectByExampleWithRowbounds(ZwzdPartyJibingExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    List<ZwzdPartyJibing> selectByExample(ZwzdPartyJibingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZwzdPartyJibing record, @Param("example") ZwzdPartyJibingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByExample(@Param("record") ZwzdPartyJibing record, @Param("example") ZwzdPartyJibingExample example);
}