package com.asiainfo.aigov.dao.healthcare.guidance;

import com.asiainfo.aigov.model.healthcare.guidance.ZwzdDisease;
import com.asiainfo.aigov.model.healthcare.guidance.ZwzdDiseaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZwzdDiseaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int countByExample(ZwzdDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int deleteByExample(ZwzdDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int deleteByPrimaryKey(String diseaseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int insert(ZwzdDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int insertSelective(ZwzdDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    List<ZwzdDisease> selectByExampleWithBLOBsWithRowbounds(ZwzdDiseaseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    List<ZwzdDisease> selectByExampleWithBLOBs(ZwzdDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    List<ZwzdDisease> selectByExampleWithRowbounds(ZwzdDiseaseExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    List<ZwzdDisease> selectByExample(ZwzdDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    ZwzdDisease selectByPrimaryKey(String diseaseid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZwzdDisease record, @Param("example") ZwzdDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") ZwzdDisease record, @Param("example") ZwzdDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int updateByExample(@Param("record") ZwzdDisease record, @Param("example") ZwzdDiseaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int updateByPrimaryKeySelective(ZwzdDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(ZwzdDisease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_DISEASE
     *
     * @mbggenerated Thu May 04 16:08:15 CST 2017
     */
    int updateByPrimaryKey(ZwzdDisease record);
}