package com.asiainfo.aigov.dao.healthcare.guidance;

import com.asiainfo.aigov.model.healthcare.guidance.ZwzdParty;
import com.asiainfo.aigov.model.healthcare.guidance.ZwzdPartyExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZwzdPartyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int countByExample(ZwzdPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int deleteByExample(ZwzdPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal partyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int insert(ZwzdParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int insertSelective(ZwzdParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    List<ZwzdParty> selectByExampleWithRowbounds(ZwzdPartyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    List<ZwzdParty> selectByExample(ZwzdPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    ZwzdParty selectByPrimaryKey(BigDecimal partyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZwzdParty record, @Param("example") ZwzdPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByExample(@Param("record") ZwzdParty record, @Param("example") ZwzdPartyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByPrimaryKeySelective(ZwzdParty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByPrimaryKey(ZwzdParty record);
}