package com.asiainfo.aigov.dao.healthcare.guidance;

import com.asiainfo.aigov.model.healthcare.guidance.ZwzdPartyJibingQuest;
import com.asiainfo.aigov.model.healthcare.guidance.ZwzdPartyJibingQuestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface ZwzdPartyJibingQuestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int countByExample(ZwzdPartyJibingQuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int deleteByExample(ZwzdPartyJibingQuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int insert(ZwzdPartyJibingQuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int insertSelective(ZwzdPartyJibingQuest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    List<ZwzdPartyJibingQuest> selectByExampleWithRowbounds(ZwzdPartyJibingQuestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    List<ZwzdPartyJibingQuest> selectByExample(ZwzdPartyJibingQuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByExampleSelective(@Param("record") ZwzdPartyJibingQuest record, @Param("example") ZwzdPartyJibingQuestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY_JIBING_QUEST
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    int updateByExample(@Param("record") ZwzdPartyJibingQuest record, @Param("example") ZwzdPartyJibingQuestExample example);
}