package com.asiainfo.aigov.dao.edot.hotLine;

import com.asiainfo.aigov.model.edot.hotLine.CityVoice;
import com.asiainfo.aigov.model.edot.hotLine.CityVoiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CityVoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int countByExample(CityVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int deleteByExample(CityVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String cityVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int insert(CityVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int insertSelective(CityVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    List<CityVoice> selectByExampleWithRowbounds(CityVoiceExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    List<CityVoice> selectByExample(CityVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    CityVoice selectByPrimaryKey(String cityVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") CityVoice record, @Param("example") CityVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int updateByExample(@Param("record") CityVoice record, @Param("example") CityVoiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(CityVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE
     *
     * @mbggenerated Wed Jun 15 16:08:08 GMT+08:00 2016
     */
    int updateByPrimaryKey(CityVoice record);
}