package com.asiainfo.aigov.dao.edot.hotLine;

import com.asiainfo.aigov.model.edot.hotLine.CityVoiceLike;
import com.asiainfo.aigov.model.edot.hotLine.CityVoiceLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CityVoiceLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int countByExample(CityVoiceLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int deleteByExample(CityVoiceLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int deleteByPrimaryKey(@Param("likeMac") String likeMac, @Param("cityVoiceId") String cityVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int insert(CityVoiceLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int insertSelective(CityVoiceLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    List<CityVoiceLike> selectByExampleWithRowbounds(CityVoiceLikeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    List<CityVoiceLike> selectByExample(CityVoiceLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    CityVoiceLike selectByPrimaryKey(@Param("likeMac") String likeMac, @Param("cityVoiceId") String cityVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int updateByExampleSelective(@Param("record") CityVoiceLike record, @Param("example") CityVoiceLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int updateByExample(@Param("record") CityVoiceLike record, @Param("example") CityVoiceLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int updateByPrimaryKeySelective(CityVoiceLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_CITY_VOICE_LIKE
     *
     * @mbggenerated Fri Jun 17 10:05:15 CST 2016
     */
    int updateByPrimaryKey(CityVoiceLike record);
}