package com.asiainfo.aigov.dao.edot.hotLine;

import com.asiainfo.aigov.model.edot.hotLine.HotMail;
import com.asiainfo.aigov.model.edot.hotLine.HotMailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

/**
* @ClassName: HotMailMapper
* @Description: 信箱持久化mapper
* @author Administrator
* @date 2017年7月24日 下午4:49:53
* 
*/
public interface HotMailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int countByExample(HotMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int deleteByExample(HotMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String hotMailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int insert(HotMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int insertSelective(HotMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    List<HotMail> selectByExampleWithRowbounds(HotMailExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    List<HotMail> selectByExample(HotMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    HotMail selectByPrimaryKey(String hotMailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") HotMail record, @Param("example") HotMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int updateByExample(@Param("record") HotMail record, @Param("example") HotMailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(HotMail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    int updateByPrimaryKey(HotMail record);
}