package com.asiainfo.aigov.dao.edot.hotLine;

import com.asiainfo.aigov.model.edot.hotLine.VideoConfig;
import com.asiainfo.aigov.model.edot.hotLine.VideoConfigExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface VideoConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    long countByExample(VideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    int deleteByExample(VideoConfigExample example);
    
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    int insert(VideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    int insertSelective(VideoConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    List<VideoConfig> selectByExampleWithRowbounds(VideoConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    List<VideoConfig> selectByExample(VideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") VideoConfig record, @Param("example") VideoConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_VIDEO_CONFIG
     *
     * @mbg.generated Fri Jul 28 16:00:30 CST 2017
     */
    int updateByExample(@Param("record") VideoConfig record, @Param("example") VideoConfigExample example);
}