package com.asiainfo.aigov.model.edot.system;

import java.util.ArrayList;
import java.util.List;

public class Feature {
	private List<Feature> child = new ArrayList<Feature>();
	private String originalId;
	
    public String getOriginalId() {
		return originalId;
	}

	public void setOriginalId(String originalId) {
		this.originalId = originalId;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.ID
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.NAME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.URL
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.ICON
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String icon;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.TYPE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.CONTENT
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.PARAM
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String param;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.STATUS
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private Short status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.ORDER_NO
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private Short orderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.DESCRIBE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String describe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.PARENT_ID
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.LEVEL_NO
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private Short levelNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.STARTDATE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String startdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.ENDDATE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String enddate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.STARTTIME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ED_FEATURE.ENDTIME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	private String endtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.ID
	 * @return  the value of ED_FEATURE.ID
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.ID
	 * @param id  the value for ED_FEATURE.ID
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.NAME
	 * @return  the value of ED_FEATURE.NAME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.NAME
	 * @param name  the value for ED_FEATURE.NAME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.URL
	 * @return  the value of ED_FEATURE.URL
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.URL
	 * @param url  the value for ED_FEATURE.URL
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.ICON
	 * @return  the value of ED_FEATURE.ICON
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getIcon() {
		return icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.ICON
	 * @param icon  the value for ED_FEATURE.ICON
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setIcon(String icon) {
		this.icon = icon;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.TYPE
	 * @return  the value of ED_FEATURE.TYPE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.TYPE
	 * @param type  the value for ED_FEATURE.TYPE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.CONTENT
	 * @return  the value of ED_FEATURE.CONTENT
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.CONTENT
	 * @param content  the value for ED_FEATURE.CONTENT
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.PARAM
	 * @return  the value of ED_FEATURE.PARAM
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getParam() {
		return param;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.PARAM
	 * @param param  the value for ED_FEATURE.PARAM
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setParam(String param) {
		this.param = param;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.STATUS
	 * @return  the value of ED_FEATURE.STATUS
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.STATUS
	 * @param status  the value for ED_FEATURE.STATUS
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.ORDER_NO
	 * @return  the value of ED_FEATURE.ORDER_NO
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public Short getOrderNo() {
		return orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.ORDER_NO
	 * @param orderNo  the value for ED_FEATURE.ORDER_NO
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setOrderNo(Short orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.DESCRIBE
	 * @return  the value of ED_FEATURE.DESCRIBE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getDescribe() {
		return describe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.DESCRIBE
	 * @param describe  the value for ED_FEATURE.DESCRIBE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setDescribe(String describe) {
		this.describe = describe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.PARENT_ID
	 * @return  the value of ED_FEATURE.PARENT_ID
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.PARENT_ID
	 * @param parentId  the value for ED_FEATURE.PARENT_ID
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.LEVEL_NO
	 * @return  the value of ED_FEATURE.LEVEL_NO
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public Short getLevelNo() {
		return levelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.LEVEL_NO
	 * @param levelNo  the value for ED_FEATURE.LEVEL_NO
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setLevelNo(Short levelNo) {
		this.levelNo = levelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.STARTDATE
	 * @return  the value of ED_FEATURE.STARTDATE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getStartdate() {
		return startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.STARTDATE
	 * @param startdate  the value for ED_FEATURE.STARTDATE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setStartdate(String startdate) {
		this.startdate = startdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.ENDDATE
	 * @return  the value of ED_FEATURE.ENDDATE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getEnddate() {
		return enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.ENDDATE
	 * @param enddate  the value for ED_FEATURE.ENDDATE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.STARTTIME
	 * @return  the value of ED_FEATURE.STARTTIME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.STARTTIME
	 * @param starttime  the value for ED_FEATURE.STARTTIME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setStarttime(String starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ED_FEATURE.ENDTIME
	 * @return  the value of ED_FEATURE.ENDTIME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public String getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ED_FEATURE.ENDTIME
	 * @param endtime  the value for ED_FEATURE.ENDTIME
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	public void setEndtime(String endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ED_FEATURE
	 * @mbg.generated  Tue Aug 08 10:37:11 CST 2017
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", id=").append(id);
		sb.append(", name=").append(name);
		sb.append(", url=").append(url);
		sb.append(", icon=").append(icon);
		sb.append(", type=").append(type);
		sb.append(", content=").append(content);
		sb.append(", param=").append(param);
		sb.append(", status=").append(status);
		sb.append(", orderNo=").append(orderNo);
		sb.append(", describe=").append(describe);
		sb.append(", parentId=").append(parentId);
		sb.append(", levelNo=").append(levelNo);
		sb.append(", startdate=").append(startdate);
		sb.append(", enddate=").append(enddate);
		sb.append(", starttime=").append(starttime);
		sb.append(", endtime=").append(endtime);
		sb.append("]");
		return sb.toString();
	}

	

	public String getAlias() {
    	return name + "[" + id + "]";
    }
    
    public List<Feature> getChild() {
		return child;
	}

	public void setChild(List<Feature> child) {
		this.child = child;
	}
}