package com.asiainfo.aigov.model.edot.system;

public class Region {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_REGION.REGION_CODE
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    private String regionCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_REGION.REGION_NAME
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_REGION.REGION_LEVEL
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    private Short regionLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_REGION.ORDER_NO
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    private Integer orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_REGION.REGION_CODE
     *
     * @return the value of SYS_REGION.REGION_CODE
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public String getRegionCode() {
        return regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_REGION.REGION_CODE
     *
     * @param regionCode the value for SYS_REGION.REGION_CODE
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public void setRegionCode(String regionCode) {
        this.regionCode = regionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_REGION.REGION_NAME
     *
     * @return the value of SYS_REGION.REGION_NAME
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_REGION.REGION_NAME
     *
     * @param regionName the value for SYS_REGION.REGION_NAME
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_REGION.REGION_LEVEL
     *
     * @return the value of SYS_REGION.REGION_LEVEL
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public Short getRegionLevel() {
        return regionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_REGION.REGION_LEVEL
     *
     * @param regionLevel the value for SYS_REGION.REGION_LEVEL
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public void setRegionLevel(Short regionLevel) {
        this.regionLevel = regionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_REGION.ORDER_NO
     *
     * @return the value of SYS_REGION.ORDER_NO
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_REGION.ORDER_NO
     *
     * @param orderNo the value for SYS_REGION.ORDER_NO
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_REGION
     *
     * @mbggenerated Sat Jun 25 17:08:03 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", regionCode=").append(regionCode);
        sb.append(", regionName=").append(regionName);
        sb.append(", regionLevel=").append(regionLevel);
        sb.append(", orderNo=").append(orderNo);
        sb.append("]");
        return sb.toString();
    }
}