package com.asiainfo.aigov.dao.healthcare.evaluate;

import com.asiainfo.aigov.model.healthcare.evaluate.PublicEvaluate;
import com.asiainfo.aigov.model.healthcare.evaluate.PublicEvaluateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicEvaluateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int countByExample(PublicEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int deleteByExample(PublicEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int deleteByPrimaryKey(String evaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int insert(PublicEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int insertSelective(PublicEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    List<PublicEvaluate> selectByExampleWithRowbounds(PublicEvaluateExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    List<PublicEvaluate> selectByExample(PublicEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    PublicEvaluate selectByPrimaryKey(String evaluateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicEvaluate record, @Param("example") PublicEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int updateByExample(@Param("record") PublicEvaluate record, @Param("example") PublicEvaluateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int updateByPrimaryKeySelective(PublicEvaluate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_EVALUATE
     *
     * @mbggenerated Mon Apr 24 20:15:15 CST 2017
     */
    int updateByPrimaryKey(PublicEvaluate record);
}