package com.asiainfo.aigov.model.edot.lifeSVC;

import java.util.ArrayList;
import java.util.List;

public class SysDataitemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public SysDataitemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNull() {
            addCriterion("item_name is null");
            return (Criteria) this;
        }

        public Criteria andItemNameIsNotNull() {
            addCriterion("item_name is not null");
            return (Criteria) this;
        }

        public Criteria andItemNameEqualTo(String value) {
            addCriterion("item_name =", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotEqualTo(String value) {
            addCriterion("item_name <>", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThan(String value) {
            addCriterion("item_name >", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameGreaterThanOrEqualTo(String value) {
            addCriterion("item_name >=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThan(String value) {
            addCriterion("item_name <", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLessThanOrEqualTo(String value) {
            addCriterion("item_name <=", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameLike(String value) {
            addCriterion("item_name like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotLike(String value) {
            addCriterion("item_name not like", value, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameIn(List<String> values) {
            addCriterion("item_name in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotIn(List<String> values) {
            addCriterion("item_name not in", values, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameBetween(String value1, String value2) {
            addCriterion("item_name between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemNameNotBetween(String value1, String value2) {
            addCriterion("item_name not between", value1, value2, "itemName");
            return (Criteria) this;
        }

        public Criteria andItemValueIsNull() {
            addCriterion("item_value is null");
            return (Criteria) this;
        }

        public Criteria andItemValueIsNotNull() {
            addCriterion("item_value is not null");
            return (Criteria) this;
        }

        public Criteria andItemValueEqualTo(String value) {
            addCriterion("item_value =", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotEqualTo(String value) {
            addCriterion("item_value <>", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueGreaterThan(String value) {
            addCriterion("item_value >", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueGreaterThanOrEqualTo(String value) {
            addCriterion("item_value >=", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLessThan(String value) {
            addCriterion("item_value <", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLessThanOrEqualTo(String value) {
            addCriterion("item_value <=", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueLike(String value) {
            addCriterion("item_value like", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotLike(String value) {
            addCriterion("item_value not like", value, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueIn(List<String> values) {
            addCriterion("item_value in", values, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotIn(List<String> values) {
            addCriterion("item_value not in", values, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueBetween(String value1, String value2) {
            addCriterion("item_value between", value1, value2, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemValueNotBetween(String value1, String value2) {
            addCriterion("item_value not between", value1, value2, "itemValue");
            return (Criteria) this;
        }

        public Criteria andItemDidIsNull() {
            addCriterion("item_did is null");
            return (Criteria) this;
        }

        public Criteria andItemDidIsNotNull() {
            addCriterion("item_did is not null");
            return (Criteria) this;
        }

        public Criteria andItemDidEqualTo(Integer value) {
            addCriterion("item_did =", value, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidNotEqualTo(Integer value) {
            addCriterion("item_did <>", value, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidGreaterThan(Integer value) {
            addCriterion("item_did >", value, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_did >=", value, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidLessThan(Integer value) {
            addCriterion("item_did <", value, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidLessThanOrEqualTo(Integer value) {
            addCriterion("item_did <=", value, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidIn(List<Integer> values) {
            addCriterion("item_did in", values, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidNotIn(List<Integer> values) {
            addCriterion("item_did not in", values, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidBetween(Integer value1, Integer value2) {
            addCriterion("item_did between", value1, value2, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemDidNotBetween(Integer value1, Integer value2) {
            addCriterion("item_did not between", value1, value2, "itemDid");
            return (Criteria) this;
        }

        public Criteria andItemNumIsNull() {
            addCriterion("item_num is null");
            return (Criteria) this;
        }

        public Criteria andItemNumIsNotNull() {
            addCriterion("item_num is not null");
            return (Criteria) this;
        }

        public Criteria andItemNumEqualTo(Integer value) {
            addCriterion("item_num =", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotEqualTo(Integer value) {
            addCriterion("item_num <>", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumGreaterThan(Integer value) {
            addCriterion("item_num >", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_num >=", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumLessThan(Integer value) {
            addCriterion("item_num <", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumLessThanOrEqualTo(Integer value) {
            addCriterion("item_num <=", value, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumIn(List<Integer> values) {
            addCriterion("item_num in", values, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotIn(List<Integer> values) {
            addCriterion("item_num not in", values, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumBetween(Integer value1, Integer value2) {
            addCriterion("item_num between", value1, value2, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemNumNotBetween(Integer value1, Integer value2) {
            addCriterion("item_num not between", value1, value2, "itemNum");
            return (Criteria) this;
        }

        public Criteria andItemLevelsIsNull() {
            addCriterion("item_levels is null");
            return (Criteria) this;
        }

        public Criteria andItemLevelsIsNotNull() {
            addCriterion("item_levels is not null");
            return (Criteria) this;
        }

        public Criteria andItemLevelsEqualTo(Integer value) {
            addCriterion("item_levels =", value, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsNotEqualTo(Integer value) {
            addCriterion("item_levels <>", value, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsGreaterThan(Integer value) {
            addCriterion("item_levels >", value, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_levels >=", value, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsLessThan(Integer value) {
            addCriterion("item_levels <", value, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsLessThanOrEqualTo(Integer value) {
            addCriterion("item_levels <=", value, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsIn(List<Integer> values) {
            addCriterion("item_levels in", values, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsNotIn(List<Integer> values) {
            addCriterion("item_levels not in", values, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsBetween(Integer value1, Integer value2) {
            addCriterion("item_levels between", value1, value2, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLevelsNotBetween(Integer value1, Integer value2) {
            addCriterion("item_levels not between", value1, value2, "itemLevels");
            return (Criteria) this;
        }

        public Criteria andItemLastIsNull() {
            addCriterion("item_last is null");
            return (Criteria) this;
        }

        public Criteria andItemLastIsNotNull() {
            addCriterion("item_last is not null");
            return (Criteria) this;
        }

        public Criteria andItemLastEqualTo(Integer value) {
            addCriterion("item_last =", value, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastNotEqualTo(Integer value) {
            addCriterion("item_last <>", value, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastGreaterThan(Integer value) {
            addCriterion("item_last >", value, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_last >=", value, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastLessThan(Integer value) {
            addCriterion("item_last <", value, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastLessThanOrEqualTo(Integer value) {
            addCriterion("item_last <=", value, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastIn(List<Integer> values) {
            addCriterion("item_last in", values, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastNotIn(List<Integer> values) {
            addCriterion("item_last not in", values, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastBetween(Integer value1, Integer value2) {
            addCriterion("item_last between", value1, value2, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemLastNotBetween(Integer value1, Integer value2) {
            addCriterion("item_last not between", value1, value2, "itemLast");
            return (Criteria) this;
        }

        public Criteria andItemRemarkIsNull() {
            addCriterion("item_remark is null");
            return (Criteria) this;
        }

        public Criteria andItemRemarkIsNotNull() {
            addCriterion("item_remark is not null");
            return (Criteria) this;
        }

        public Criteria andItemRemarkEqualTo(String value) {
            addCriterion("item_remark =", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkNotEqualTo(String value) {
            addCriterion("item_remark <>", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkGreaterThan(String value) {
            addCriterion("item_remark >", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("item_remark >=", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkLessThan(String value) {
            addCriterion("item_remark <", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkLessThanOrEqualTo(String value) {
            addCriterion("item_remark <=", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkLike(String value) {
            addCriterion("item_remark like", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkNotLike(String value) {
            addCriterion("item_remark not like", value, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkIn(List<String> values) {
            addCriterion("item_remark in", values, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkNotIn(List<String> values) {
            addCriterion("item_remark not in", values, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkBetween(String value1, String value2) {
            addCriterion("item_remark between", value1, value2, "itemRemark");
            return (Criteria) this;
        }

        public Criteria andItemRemarkNotBetween(String value1, String value2) {
            addCriterion("item_remark not between", value1, value2, "itemRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dataitem
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 25 13:01:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_dataitem
     *
     * @mbggenerated Thu Aug 25 13:01:07 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}