package com.asiainfo.aigov.model.edot.lifeSVC;

import java.util.ArrayList;
import java.util.List;

public class WebServiceCommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public WebServiceCommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(Integer value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(Integer value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(Integer value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(Integer value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(Integer value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<Integer> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<Integer> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(Integer value1, Integer value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Integer value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Integer value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Integer value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Integer value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Integer> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Integer> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Integer value1, Integer value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andCommentMydIsNull() {
            addCriterion("comment_myd is null");
            return (Criteria) this;
        }

        public Criteria andCommentMydIsNotNull() {
            addCriterion("comment_myd is not null");
            return (Criteria) this;
        }

        public Criteria andCommentMydEqualTo(String value) {
            addCriterion("comment_myd =", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydNotEqualTo(String value) {
            addCriterion("comment_myd <>", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydGreaterThan(String value) {
            addCriterion("comment_myd >", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydGreaterThanOrEqualTo(String value) {
            addCriterion("comment_myd >=", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydLessThan(String value) {
            addCriterion("comment_myd <", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydLessThanOrEqualTo(String value) {
            addCriterion("comment_myd <=", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydLike(String value) {
            addCriterion("comment_myd like", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydNotLike(String value) {
            addCriterion("comment_myd not like", value, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydIn(List<String> values) {
            addCriterion("comment_myd in", values, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydNotIn(List<String> values) {
            addCriterion("comment_myd not in", values, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydBetween(String value1, String value2) {
            addCriterion("comment_myd between", value1, value2, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentMydNotBetween(String value1, String value2) {
            addCriterion("comment_myd not between", value1, value2, "commentMyd");
            return (Criteria) this;
        }

        public Criteria andCommentTxtIsNull() {
            addCriterion("comment_txt is null");
            return (Criteria) this;
        }

        public Criteria andCommentTxtIsNotNull() {
            addCriterion("comment_txt is not null");
            return (Criteria) this;
        }

        public Criteria andCommentTxtEqualTo(String value) {
            addCriterion("comment_txt =", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtNotEqualTo(String value) {
            addCriterion("comment_txt <>", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtGreaterThan(String value) {
            addCriterion("comment_txt >", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtGreaterThanOrEqualTo(String value) {
            addCriterion("comment_txt >=", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtLessThan(String value) {
            addCriterion("comment_txt <", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtLessThanOrEqualTo(String value) {
            addCriterion("comment_txt <=", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtLike(String value) {
            addCriterion("comment_txt like", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtNotLike(String value) {
            addCriterion("comment_txt not like", value, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtIn(List<String> values) {
            addCriterion("comment_txt in", values, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtNotIn(List<String> values) {
            addCriterion("comment_txt not in", values, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtBetween(String value1, String value2) {
            addCriterion("comment_txt between", value1, value2, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCommentTxtNotBetween(String value1, String value2) {
            addCriterion("comment_txt not between", value1, value2, "commentTxt");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("create_date like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("create_date not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andReplyTxtIsNull() {
            addCriterion("reply_txt is null");
            return (Criteria) this;
        }

        public Criteria andReplyTxtIsNotNull() {
            addCriterion("reply_txt is not null");
            return (Criteria) this;
        }

        public Criteria andReplyTxtEqualTo(String value) {
            addCriterion("reply_txt =", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtNotEqualTo(String value) {
            addCriterion("reply_txt <>", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtGreaterThan(String value) {
            addCriterion("reply_txt >", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtGreaterThanOrEqualTo(String value) {
            addCriterion("reply_txt >=", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtLessThan(String value) {
            addCriterion("reply_txt <", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtLessThanOrEqualTo(String value) {
            addCriterion("reply_txt <=", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtLike(String value) {
            addCriterion("reply_txt like", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtNotLike(String value) {
            addCriterion("reply_txt not like", value, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtIn(List<String> values) {
            addCriterion("reply_txt in", values, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtNotIn(List<String> values) {
            addCriterion("reply_txt not in", values, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtBetween(String value1, String value2) {
            addCriterion("reply_txt between", value1, value2, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyTxtNotBetween(String value1, String value2) {
            addCriterion("reply_txt not between", value1, value2, "replyTxt");
            return (Criteria) this;
        }

        public Criteria andReplyDateIsNull() {
            addCriterion("reply_date is null");
            return (Criteria) this;
        }

        public Criteria andReplyDateIsNotNull() {
            addCriterion("reply_date is not null");
            return (Criteria) this;
        }

        public Criteria andReplyDateEqualTo(String value) {
            addCriterion("reply_date =", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateNotEqualTo(String value) {
            addCriterion("reply_date <>", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateGreaterThan(String value) {
            addCriterion("reply_date >", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateGreaterThanOrEqualTo(String value) {
            addCriterion("reply_date >=", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateLessThan(String value) {
            addCriterion("reply_date <", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateLessThanOrEqualTo(String value) {
            addCriterion("reply_date <=", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateLike(String value) {
            addCriterion("reply_date like", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateNotLike(String value) {
            addCriterion("reply_date not like", value, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateIn(List<String> values) {
            addCriterion("reply_date in", values, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateNotIn(List<String> values) {
            addCriterion("reply_date not in", values, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateBetween(String value1, String value2) {
            addCriterion("reply_date between", value1, value2, "replyDate");
            return (Criteria) this;
        }

        public Criteria andReplyDateNotBetween(String value1, String value2) {
            addCriterion("reply_date not between", value1, value2, "replyDate");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(String value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(String value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(String value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(String value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(String value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLike(String value) {
            addCriterion("is_del like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotLike(String value) {
            addCriterion("is_del not like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<String> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<String> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(String value1, String value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(String value1, String value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_service_comment
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 25 13:04:57 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}