package com.asiainfo.aigov.model.edot.lifeSVC;

import java.util.ArrayList;
import java.util.List;

public class WebServiceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public WebServiceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andServiceIdIsNull() {
            addCriterion("service_id is null");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNotNull() {
            addCriterion("service_id is not null");
            return (Criteria) this;
        }

        public Criteria andServiceIdEqualTo(Integer value) {
            addCriterion("service_id =", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotEqualTo(Integer value) {
            addCriterion("service_id <>", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThan(Integer value) {
            addCriterion("service_id >", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_id >=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThan(Integer value) {
            addCriterion("service_id <", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThanOrEqualTo(Integer value) {
            addCriterion("service_id <=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIn(List<Integer> values) {
            addCriterion("service_id in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotIn(List<Integer> values) {
            addCriterion("service_id not in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdBetween(Integer value1, Integer value2) {
            addCriterion("service_id between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("service_id not between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(Integer value) {
            addCriterion("member_id =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(Integer value) {
            addCriterion("member_id <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(Integer value) {
            addCriterion("member_id >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_id >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(Integer value) {
            addCriterion("member_id <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("member_id <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<Integer> values) {
            addCriterion("member_id in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<Integer> values) {
            addCriterion("member_id not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(Integer value1, Integer value2) {
            addCriterion("member_id between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("member_id not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNull() {
            addCriterion("service_type is null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIsNotNull() {
            addCriterion("service_type is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTypeEqualTo(Integer value) {
            addCriterion("service_type =", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotEqualTo(Integer value) {
            addCriterion("service_type <>", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThan(Integer value) {
            addCriterion("service_type >", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_type >=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThan(Integer value) {
            addCriterion("service_type <", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("service_type <=", value, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeIn(List<Integer> values) {
            addCriterion("service_type in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotIn(List<Integer> values) {
            addCriterion("service_type not in", values, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeBetween(Integer value1, Integer value2) {
            addCriterion("service_type between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("service_type not between", value1, value2, "serviceType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeIsNull() {
            addCriterion("service_two_type is null");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeIsNotNull() {
            addCriterion("service_two_type is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeEqualTo(Integer value) {
            addCriterion("service_two_type =", value, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeNotEqualTo(Integer value) {
            addCriterion("service_two_type <>", value, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeGreaterThan(Integer value) {
            addCriterion("service_two_type >", value, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_two_type >=", value, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeLessThan(Integer value) {
            addCriterion("service_two_type <", value, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeLessThanOrEqualTo(Integer value) {
            addCriterion("service_two_type <=", value, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeIn(List<Integer> values) {
            addCriterion("service_two_type in", values, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeNotIn(List<Integer> values) {
            addCriterion("service_two_type not in", values, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeBetween(Integer value1, Integer value2) {
            addCriterion("service_two_type between", value1, value2, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceTwoTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("service_two_type not between", value1, value2, "serviceTwoType");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNull() {
            addCriterion("service_name is null");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNotNull() {
            addCriterion("service_name is not null");
            return (Criteria) this;
        }

        public Criteria andServiceNameEqualTo(String value) {
            addCriterion("service_name =", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotEqualTo(String value) {
            addCriterion("service_name <>", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThan(String value) {
            addCriterion("service_name >", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThanOrEqualTo(String value) {
            addCriterion("service_name >=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThan(String value) {
            addCriterion("service_name <", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThanOrEqualTo(String value) {
            addCriterion("service_name <=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLike(String value) {
            addCriterion("service_name like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotLike(String value) {
            addCriterion("service_name not like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameIn(List<String> values) {
            addCriterion("service_name in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotIn(List<String> values) {
            addCriterion("service_name not in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameBetween(String value1, String value2) {
            addCriterion("service_name between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotBetween(String value1, String value2) {
            addCriterion("service_name not between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceLogoIsNull() {
            addCriterion("service_logo is null");
            return (Criteria) this;
        }

        public Criteria andServiceLogoIsNotNull() {
            addCriterion("service_logo is not null");
            return (Criteria) this;
        }

        public Criteria andServiceLogoEqualTo(String value) {
            addCriterion("service_logo =", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoNotEqualTo(String value) {
            addCriterion("service_logo <>", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoGreaterThan(String value) {
            addCriterion("service_logo >", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoGreaterThanOrEqualTo(String value) {
            addCriterion("service_logo >=", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoLessThan(String value) {
            addCriterion("service_logo <", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoLessThanOrEqualTo(String value) {
            addCriterion("service_logo <=", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoLike(String value) {
            addCriterion("service_logo like", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoNotLike(String value) {
            addCriterion("service_logo not like", value, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoIn(List<String> values) {
            addCriterion("service_logo in", values, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoNotIn(List<String> values) {
            addCriterion("service_logo not in", values, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoBetween(String value1, String value2) {
            addCriterion("service_logo between", value1, value2, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLogoNotBetween(String value1, String value2) {
            addCriterion("service_logo not between", value1, value2, "serviceLogo");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanIsNull() {
            addCriterion("service_linkman is null");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanIsNotNull() {
            addCriterion("service_linkman is not null");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanEqualTo(String value) {
            addCriterion("service_linkman =", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanNotEqualTo(String value) {
            addCriterion("service_linkman <>", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanGreaterThan(String value) {
            addCriterion("service_linkman >", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanGreaterThanOrEqualTo(String value) {
            addCriterion("service_linkman >=", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanLessThan(String value) {
            addCriterion("service_linkman <", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanLessThanOrEqualTo(String value) {
            addCriterion("service_linkman <=", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanLike(String value) {
            addCriterion("service_linkman like", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanNotLike(String value) {
            addCriterion("service_linkman not like", value, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanIn(List<String> values) {
            addCriterion("service_linkman in", values, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanNotIn(List<String> values) {
            addCriterion("service_linkman not in", values, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanBetween(String value1, String value2) {
            addCriterion("service_linkman between", value1, value2, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServiceLinkmanNotBetween(String value1, String value2) {
            addCriterion("service_linkman not between", value1, value2, "serviceLinkman");
            return (Criteria) this;
        }

        public Criteria andServicePhoneIsNull() {
            addCriterion("service_phone is null");
            return (Criteria) this;
        }

        public Criteria andServicePhoneIsNotNull() {
            addCriterion("service_phone is not null");
            return (Criteria) this;
        }

        public Criteria andServicePhoneEqualTo(String value) {
            addCriterion("service_phone =", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotEqualTo(String value) {
            addCriterion("service_phone <>", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneGreaterThan(String value) {
            addCriterion("service_phone >", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("service_phone >=", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneLessThan(String value) {
            addCriterion("service_phone <", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneLessThanOrEqualTo(String value) {
            addCriterion("service_phone <=", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneLike(String value) {
            addCriterion("service_phone like", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotLike(String value) {
            addCriterion("service_phone not like", value, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneIn(List<String> values) {
            addCriterion("service_phone in", values, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotIn(List<String> values) {
            addCriterion("service_phone not in", values, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneBetween(String value1, String value2) {
            addCriterion("service_phone between", value1, value2, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServicePhoneNotBetween(String value1, String value2) {
            addCriterion("service_phone not between", value1, value2, "servicePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneIsNull() {
            addCriterion("service_mobile_phone is null");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneIsNotNull() {
            addCriterion("service_mobile_phone is not null");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneEqualTo(String value) {
            addCriterion("service_mobile_phone =", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneNotEqualTo(String value) {
            addCriterion("service_mobile_phone <>", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneGreaterThan(String value) {
            addCriterion("service_mobile_phone >", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneGreaterThanOrEqualTo(String value) {
            addCriterion("service_mobile_phone >=", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneLessThan(String value) {
            addCriterion("service_mobile_phone <", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneLessThanOrEqualTo(String value) {
            addCriterion("service_mobile_phone <=", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneLike(String value) {
            addCriterion("service_mobile_phone like", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneNotLike(String value) {
            addCriterion("service_mobile_phone not like", value, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneIn(List<String> values) {
            addCriterion("service_mobile_phone in", values, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneNotIn(List<String> values) {
            addCriterion("service_mobile_phone not in", values, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneBetween(String value1, String value2) {
            addCriterion("service_mobile_phone between", value1, value2, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceMobilePhoneNotBetween(String value1, String value2) {
            addCriterion("service_mobile_phone not between", value1, value2, "serviceMobilePhone");
            return (Criteria) this;
        }

        public Criteria andServiceScopeIsNull() {
            addCriterion("service_scope is null");
            return (Criteria) this;
        }

        public Criteria andServiceScopeIsNotNull() {
            addCriterion("service_scope is not null");
            return (Criteria) this;
        }

        public Criteria andServiceScopeEqualTo(String value) {
            addCriterion("service_scope =", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeNotEqualTo(String value) {
            addCriterion("service_scope <>", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeGreaterThan(String value) {
            addCriterion("service_scope >", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeGreaterThanOrEqualTo(String value) {
            addCriterion("service_scope >=", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeLessThan(String value) {
            addCriterion("service_scope <", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeLessThanOrEqualTo(String value) {
            addCriterion("service_scope <=", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeLike(String value) {
            addCriterion("service_scope like", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeNotLike(String value) {
            addCriterion("service_scope not like", value, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeIn(List<String> values) {
            addCriterion("service_scope in", values, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeNotIn(List<String> values) {
            addCriterion("service_scope not in", values, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeBetween(String value1, String value2) {
            addCriterion("service_scope between", value1, value2, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceScopeNotBetween(String value1, String value2) {
            addCriterion("service_scope not between", value1, value2, "serviceScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeIsNull() {
            addCriterion("service_two_scope is null");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeIsNotNull() {
            addCriterion("service_two_scope is not null");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeEqualTo(String value) {
            addCriterion("service_two_scope =", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeNotEqualTo(String value) {
            addCriterion("service_two_scope <>", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeGreaterThan(String value) {
            addCriterion("service_two_scope >", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeGreaterThanOrEqualTo(String value) {
            addCriterion("service_two_scope >=", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeLessThan(String value) {
            addCriterion("service_two_scope <", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeLessThanOrEqualTo(String value) {
            addCriterion("service_two_scope <=", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeLike(String value) {
            addCriterion("service_two_scope like", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeNotLike(String value) {
            addCriterion("service_two_scope not like", value, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeIn(List<String> values) {
            addCriterion("service_two_scope in", values, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeNotIn(List<String> values) {
            addCriterion("service_two_scope not in", values, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeBetween(String value1, String value2) {
            addCriterion("service_two_scope between", value1, value2, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServiceTwoScopeNotBetween(String value1, String value2) {
            addCriterion("service_two_scope not between", value1, value2, "serviceTwoScope");
            return (Criteria) this;
        }

        public Criteria andServicePriceIsNull() {
            addCriterion("service_price is null");
            return (Criteria) this;
        }

        public Criteria andServicePriceIsNotNull() {
            addCriterion("service_price is not null");
            return (Criteria) this;
        }

        public Criteria andServicePriceEqualTo(String value) {
            addCriterion("service_price =", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotEqualTo(String value) {
            addCriterion("service_price <>", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceGreaterThan(String value) {
            addCriterion("service_price >", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceGreaterThanOrEqualTo(String value) {
            addCriterion("service_price >=", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLessThan(String value) {
            addCriterion("service_price <", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLessThanOrEqualTo(String value) {
            addCriterion("service_price <=", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLike(String value) {
            addCriterion("service_price like", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotLike(String value) {
            addCriterion("service_price not like", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceIn(List<String> values) {
            addCriterion("service_price in", values, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotIn(List<String> values) {
            addCriterion("service_price not in", values, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceBetween(String value1, String value2) {
            addCriterion("service_price between", value1, value2, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotBetween(String value1, String value2) {
            addCriterion("service_price not between", value1, value2, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateIsNull() {
            addCriterion("service_hours_date is null");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateIsNotNull() {
            addCriterion("service_hours_date is not null");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateEqualTo(String value) {
            addCriterion("service_hours_date =", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateNotEqualTo(String value) {
            addCriterion("service_hours_date <>", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateGreaterThan(String value) {
            addCriterion("service_hours_date >", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateGreaterThanOrEqualTo(String value) {
            addCriterion("service_hours_date >=", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateLessThan(String value) {
            addCriterion("service_hours_date <", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateLessThanOrEqualTo(String value) {
            addCriterion("service_hours_date <=", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateLike(String value) {
            addCriterion("service_hours_date like", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateNotLike(String value) {
            addCriterion("service_hours_date not like", value, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateIn(List<String> values) {
            addCriterion("service_hours_date in", values, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateNotIn(List<String> values) {
            addCriterion("service_hours_date not in", values, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateBetween(String value1, String value2) {
            addCriterion("service_hours_date between", value1, value2, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceHoursDateNotBetween(String value1, String value2) {
            addCriterion("service_hours_date not between", value1, value2, "serviceHoursDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateIsNull() {
            addCriterion("service_effective_date is null");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateIsNotNull() {
            addCriterion("service_effective_date is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateEqualTo(String value) {
            addCriterion("service_effective_date =", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateNotEqualTo(String value) {
            addCriterion("service_effective_date <>", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateGreaterThan(String value) {
            addCriterion("service_effective_date >", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateGreaterThanOrEqualTo(String value) {
            addCriterion("service_effective_date >=", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateLessThan(String value) {
            addCriterion("service_effective_date <", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateLessThanOrEqualTo(String value) {
            addCriterion("service_effective_date <=", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateLike(String value) {
            addCriterion("service_effective_date like", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateNotLike(String value) {
            addCriterion("service_effective_date not like", value, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateIn(List<String> values) {
            addCriterion("service_effective_date in", values, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateNotIn(List<String> values) {
            addCriterion("service_effective_date not in", values, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateBetween(String value1, String value2) {
            addCriterion("service_effective_date between", value1, value2, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceEffectiveDateNotBetween(String value1, String value2) {
            addCriterion("service_effective_date not between", value1, value2, "serviceEffectiveDate");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractIsNull() {
            addCriterion("service_abstract is null");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractIsNotNull() {
            addCriterion("service_abstract is not null");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractEqualTo(String value) {
            addCriterion("service_abstract =", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractNotEqualTo(String value) {
            addCriterion("service_abstract <>", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractGreaterThan(String value) {
            addCriterion("service_abstract >", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractGreaterThanOrEqualTo(String value) {
            addCriterion("service_abstract >=", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractLessThan(String value) {
            addCriterion("service_abstract <", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractLessThanOrEqualTo(String value) {
            addCriterion("service_abstract <=", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractLike(String value) {
            addCriterion("service_abstract like", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractNotLike(String value) {
            addCriterion("service_abstract not like", value, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractIn(List<String> values) {
            addCriterion("service_abstract in", values, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractNotIn(List<String> values) {
            addCriterion("service_abstract not in", values, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractBetween(String value1, String value2) {
            addCriterion("service_abstract between", value1, value2, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceAbstractNotBetween(String value1, String value2) {
            addCriterion("service_abstract not between", value1, value2, "serviceAbstract");
            return (Criteria) this;
        }

        public Criteria andServiceSalesIsNull() {
            addCriterion("service_sales is null");
            return (Criteria) this;
        }

        public Criteria andServiceSalesIsNotNull() {
            addCriterion("service_sales is not null");
            return (Criteria) this;
        }

        public Criteria andServiceSalesEqualTo(Integer value) {
            addCriterion("service_sales =", value, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesNotEqualTo(Integer value) {
            addCriterion("service_sales <>", value, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesGreaterThan(Integer value) {
            addCriterion("service_sales >", value, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_sales >=", value, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesLessThan(Integer value) {
            addCriterion("service_sales <", value, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesLessThanOrEqualTo(Integer value) {
            addCriterion("service_sales <=", value, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesIn(List<Integer> values) {
            addCriterion("service_sales in", values, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesNotIn(List<Integer> values) {
            addCriterion("service_sales not in", values, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesBetween(Integer value1, Integer value2) {
            addCriterion("service_sales between", value1, value2, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceSalesNotBetween(Integer value1, Integer value2) {
            addCriterion("service_sales not between", value1, value2, "serviceSales");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumIsNull() {
            addCriterion("service_checknum is null");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumIsNotNull() {
            addCriterion("service_checknum is not null");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumEqualTo(Integer value) {
            addCriterion("service_checknum =", value, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumNotEqualTo(Integer value) {
            addCriterion("service_checknum <>", value, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumGreaterThan(Integer value) {
            addCriterion("service_checknum >", value, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_checknum >=", value, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumLessThan(Integer value) {
            addCriterion("service_checknum <", value, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumLessThanOrEqualTo(Integer value) {
            addCriterion("service_checknum <=", value, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumIn(List<Integer> values) {
            addCriterion("service_checknum in", values, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumNotIn(List<Integer> values) {
            addCriterion("service_checknum not in", values, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumBetween(Integer value1, Integer value2) {
            addCriterion("service_checknum between", value1, value2, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andServiceChecknumNotBetween(Integer value1, Integer value2) {
            addCriterion("service_checknum not between", value1, value2, "serviceChecknum");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(String value) {
            addCriterion("create_date =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(String value) {
            addCriterion("create_date <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(String value) {
            addCriterion("create_date >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(String value) {
            addCriterion("create_date >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(String value) {
            addCriterion("create_date <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(String value) {
            addCriterion("create_date <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLike(String value) {
            addCriterion("create_date like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotLike(String value) {
            addCriterion("create_date not like", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<String> values) {
            addCriterion("create_date in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<String> values) {
            addCriterion("create_date not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(String value1, String value2) {
            addCriterion("create_date between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(String value1, String value2) {
            addCriterion("create_date not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andServiceStateIsNull() {
            addCriterion("service_state is null");
            return (Criteria) this;
        }

        public Criteria andServiceStateIsNotNull() {
            addCriterion("service_state is not null");
            return (Criteria) this;
        }

        public Criteria andServiceStateEqualTo(String value) {
            addCriterion("service_state =", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateNotEqualTo(String value) {
            addCriterion("service_state <>", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateGreaterThan(String value) {
            addCriterion("service_state >", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateGreaterThanOrEqualTo(String value) {
            addCriterion("service_state >=", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateLessThan(String value) {
            addCriterion("service_state <", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateLessThanOrEqualTo(String value) {
            addCriterion("service_state <=", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateLike(String value) {
            addCriterion("service_state like", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateNotLike(String value) {
            addCriterion("service_state not like", value, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateIn(List<String> values) {
            addCriterion("service_state in", values, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateNotIn(List<String> values) {
            addCriterion("service_state not in", values, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateBetween(String value1, String value2) {
            addCriterion("service_state between", value1, value2, "serviceState");
            return (Criteria) this;
        }

        public Criteria andServiceStateNotBetween(String value1, String value2) {
            addCriterion("service_state not between", value1, value2, "serviceState");
            return (Criteria) this;
        }

        public Criteria andIsTuijianIsNull() {
            addCriterion("is_tuijian is null");
            return (Criteria) this;
        }

        public Criteria andIsTuijianIsNotNull() {
            addCriterion("is_tuijian is not null");
            return (Criteria) this;
        }

        public Criteria andIsTuijianEqualTo(String value) {
            addCriterion("is_tuijian =", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianNotEqualTo(String value) {
            addCriterion("is_tuijian <>", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianGreaterThan(String value) {
            addCriterion("is_tuijian >", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianGreaterThanOrEqualTo(String value) {
            addCriterion("is_tuijian >=", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianLessThan(String value) {
            addCriterion("is_tuijian <", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianLessThanOrEqualTo(String value) {
            addCriterion("is_tuijian <=", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianLike(String value) {
            addCriterion("is_tuijian like", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianNotLike(String value) {
            addCriterion("is_tuijian not like", value, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianIn(List<String> values) {
            addCriterion("is_tuijian in", values, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianNotIn(List<String> values) {
            addCriterion("is_tuijian not in", values, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianBetween(String value1, String value2) {
            addCriterion("is_tuijian between", value1, value2, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsTuijianNotBetween(String value1, String value2) {
            addCriterion("is_tuijian not between", value1, value2, "isTuijian");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNull() {
            addCriterion("is_del is null");
            return (Criteria) this;
        }

        public Criteria andIsDelIsNotNull() {
            addCriterion("is_del is not null");
            return (Criteria) this;
        }

        public Criteria andIsDelEqualTo(String value) {
            addCriterion("is_del =", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotEqualTo(String value) {
            addCriterion("is_del <>", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThan(String value) {
            addCriterion("is_del >", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelGreaterThanOrEqualTo(String value) {
            addCriterion("is_del >=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThan(String value) {
            addCriterion("is_del <", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLessThanOrEqualTo(String value) {
            addCriterion("is_del <=", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelLike(String value) {
            addCriterion("is_del like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotLike(String value) {
            addCriterion("is_del not like", value, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelIn(List<String> values) {
            addCriterion("is_del in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotIn(List<String> values) {
            addCriterion("is_del not in", values, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelBetween(String value1, String value2) {
            addCriterion("is_del between", value1, value2, "isDel");
            return (Criteria) this;
        }

        public Criteria andIsDelNotBetween(String value1, String value2) {
            addCriterion("is_del not between", value1, value2, "isDel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_service
     *
     * @mbggenerated do_not_delete_during_merge Thu Aug 25 13:03:28 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table web_service
     *
     * @mbggenerated Thu Aug 25 13:03:28 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}