package com.asiainfo.aigov.model.edot.lifeSVC;

public class WebServiceComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.comment_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private Integer commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.item_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.member_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.comment_myd
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private String commentMyd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.comment_txt
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private String commentTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.create_date
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private String createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.reply_txt
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private String replyTxt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.reply_date
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private String replyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_service_comment.is_del
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    private String isDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.comment_id
     *
     * @return the value of web_service_comment.comment_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public Integer getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.comment_id
     *
     * @param commentId the value for web_service_comment.comment_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setCommentId(Integer commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.item_id
     *
     * @return the value of web_service_comment.item_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.item_id
     *
     * @param itemId the value for web_service_comment.item_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.member_id
     *
     * @return the value of web_service_comment.member_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.member_id
     *
     * @param memberId the value for web_service_comment.member_id
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.comment_myd
     *
     * @return the value of web_service_comment.comment_myd
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public String getCommentMyd() {
        return commentMyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.comment_myd
     *
     * @param commentMyd the value for web_service_comment.comment_myd
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setCommentMyd(String commentMyd) {
        this.commentMyd = commentMyd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.comment_txt
     *
     * @return the value of web_service_comment.comment_txt
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public String getCommentTxt() {
        return commentTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.comment_txt
     *
     * @param commentTxt the value for web_service_comment.comment_txt
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setCommentTxt(String commentTxt) {
        this.commentTxt = commentTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.create_date
     *
     * @return the value of web_service_comment.create_date
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.create_date
     *
     * @param createDate the value for web_service_comment.create_date
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setCreateDate(String createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.reply_txt
     *
     * @return the value of web_service_comment.reply_txt
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public String getReplyTxt() {
        return replyTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.reply_txt
     *
     * @param replyTxt the value for web_service_comment.reply_txt
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setReplyTxt(String replyTxt) {
        this.replyTxt = replyTxt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.reply_date
     *
     * @return the value of web_service_comment.reply_date
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public String getReplyDate() {
        return replyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.reply_date
     *
     * @param replyDate the value for web_service_comment.reply_date
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setReplyDate(String replyDate) {
        this.replyDate = replyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_service_comment.is_del
     *
     * @return the value of web_service_comment.is_del
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public String getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_service_comment.is_del
     *
     * @param isDel the value for web_service_comment.is_del
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    public void setIsDel(String isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_comment
     *
     * @mbggenerated Thu Aug 25 13:04:57 CST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", commentId=").append(commentId);
        sb.append(", itemId=").append(itemId);
        sb.append(", memberId=").append(memberId);
        sb.append(", commentMyd=").append(commentMyd);
        sb.append(", commentTxt=").append(commentTxt);
        sb.append(", createDate=").append(createDate);
        sb.append(", replyTxt=").append(replyTxt);
        sb.append(", replyDate=").append(replyDate);
        sb.append(", isDel=").append(isDel);
        sb.append("]");
        return sb.toString();
    }
}