package com.asiainfo.aigov.healthcare.dao;

import com.asiainfo.aigov.healthcare.model.JkghAppMessage;
import com.asiainfo.aigov.healthcare.model.JkghAppMessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

/**
* @ClassName: JkghAppMessageMapper
* @Description: TODO(这里用一句话描述这个类的作用)
* @author Administrator
* @date 2017年7月25日 上午11:58:58
* 
*/
public interface JkghAppMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int countByExample(JkghAppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int deleteByExample(JkghAppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int insert(JkghAppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int insertSelective(JkghAppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    List<JkghAppMessage> selectByExampleWithRowbounds(JkghAppMessageExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    List<JkghAppMessage> selectByExample(JkghAppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    JkghAppMessage selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int updateByExampleSelective(@Param("record") JkghAppMessage record, @Param("example") JkghAppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int updateByExample(@Param("record") JkghAppMessage record, @Param("example") JkghAppMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int updateByPrimaryKeySelective(JkghAppMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JKGH_APP_MESSAGE
     *
     * @mbggenerated Tue Sep 06 11:41:28 CST 2016
     */
    int updateByPrimaryKey(JkghAppMessage record);
}