package com.asiainfo.aigov.dao.healthcare.attention;

import com.asiainfo.aigov.model.healthcare.attention.PublicUserDoctorAttention;
import com.asiainfo.aigov.model.healthcare.attention.PublicUserDoctorAttentionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicUserDoctorAttentionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int countByExample(PublicUserDoctorAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int deleteByExample(PublicUserDoctorAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int insert(PublicUserDoctorAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int insertSelective(PublicUserDoctorAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    List<PublicUserDoctorAttention> selectByExampleWithRowbounds(PublicUserDoctorAttentionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    List<PublicUserDoctorAttention> selectByExample(PublicUserDoctorAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    PublicUserDoctorAttention selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicUserDoctorAttention record, @Param("example") PublicUserDoctorAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int updateByExample(@Param("record") PublicUserDoctorAttention record, @Param("example") PublicUserDoctorAttentionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int updateByPrimaryKeySelective(PublicUserDoctorAttention record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_USER_DOCTOR_ATTENTION
     *
     * @mbggenerated Thu Apr 20 15:54:04 CST 2017
     */
    int updateByPrimaryKey(PublicUserDoctorAttention record);
}