package com.asiainfo.aigov.model.edot.work;

import java.util.Date;

/**
* @ClassName: BusinessClass
* @Description: mybatis生成的实体类
* @author Administrator
* @date 2017年7月25日 上午10:29:03
* 
*/
public class BusinessClass {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_WORK_BUSINESS_CLASS.ID
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_WORK_BUSINESS_CLASS.COLUNAME
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    private String coluname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_WORK_BUSINESS_CLASS.COLUPARENTID
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    private String coluparentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_WORK_BUSINESS_CLASS.COLUSORT
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    private String colusort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_WORK_BUSINESS_CLASS.IMGURL
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    private String imgurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_WORK_BUSINESS_CLASS.UPDATE_TIME
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_WORK_BUSINESS_CLASS.ID
     *
     * @return the value of ED_WORK_BUSINESS_CLASS.ID
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_WORK_BUSINESS_CLASS.ID
     *
     * @param id the value for ED_WORK_BUSINESS_CLASS.ID
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_WORK_BUSINESS_CLASS.COLUNAME
     *
     * @return the value of ED_WORK_BUSINESS_CLASS.COLUNAME
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public String getColuname() {
        return coluname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_WORK_BUSINESS_CLASS.COLUNAME
     *
     * @param coluname the value for ED_WORK_BUSINESS_CLASS.COLUNAME
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public void setColuname(String coluname) {
        this.coluname = coluname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_WORK_BUSINESS_CLASS.COLUPARENTID
     *
     * @return the value of ED_WORK_BUSINESS_CLASS.COLUPARENTID
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public String getColuparentid() {
        return coluparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_WORK_BUSINESS_CLASS.COLUPARENTID
     *
     * @param coluparentid the value for ED_WORK_BUSINESS_CLASS.COLUPARENTID
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public void setColuparentid(String coluparentid) {
        this.coluparentid = coluparentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_WORK_BUSINESS_CLASS.COLUSORT
     *
     * @return the value of ED_WORK_BUSINESS_CLASS.COLUSORT
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public String getColusort() {
        return colusort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_WORK_BUSINESS_CLASS.COLUSORT
     *
     * @param colusort the value for ED_WORK_BUSINESS_CLASS.COLUSORT
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public void setColusort(String colusort) {
        this.colusort = colusort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_WORK_BUSINESS_CLASS.IMGURL
     *
     * @return the value of ED_WORK_BUSINESS_CLASS.IMGURL
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_WORK_BUSINESS_CLASS.IMGURL
     *
     * @param imgurl the value for ED_WORK_BUSINESS_CLASS.IMGURL
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_WORK_BUSINESS_CLASS.UPDATE_TIME
     *
     * @return the value of ED_WORK_BUSINESS_CLASS.UPDATE_TIME
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_WORK_BUSINESS_CLASS.UPDATE_TIME
     *
     * @param updateTime the value for ED_WORK_BUSINESS_CLASS.UPDATE_TIME
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_BUSINESS_CLASS
     *
     * @mbggenerated Tue Jul 12 11:37:37 GMT+08:00 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", coluname=").append(coluname);
        sb.append(", coluparentid=").append(coluparentid);
        sb.append(", colusort=").append(colusort);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}