package com.asiainfo.aigov.model.edot.work;

import java.util.Date;

public class UserWork {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_USER_WORK.USER_WORK_NO
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    private String userWorkNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_USER_WORK.USER_ID
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_USER_WORK.WORK_CODE
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    private String workCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_USER_WORK.CREATE_TIME
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_USER_WORK.STATUS
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_USER_WORK.STATUS_NAME
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    private String statusName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_USER_WORK.READ_STATUS
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    private String readStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_USER_WORK.USER_WORK_NO
     *
     * @return the value of ED_USER_WORK.USER_WORK_NO
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public String getUserWorkNo() {
        return userWorkNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_USER_WORK.USER_WORK_NO
     *
     * @param userWorkNo the value for ED_USER_WORK.USER_WORK_NO
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public void setUserWorkNo(String userWorkNo) {
        this.userWorkNo = userWorkNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_USER_WORK.USER_ID
     *
     * @return the value of ED_USER_WORK.USER_ID
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_USER_WORK.USER_ID
     *
     * @param userId the value for ED_USER_WORK.USER_ID
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_USER_WORK.WORK_CODE
     *
     * @return the value of ED_USER_WORK.WORK_CODE
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public String getWorkCode() {
        return workCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_USER_WORK.WORK_CODE
     *
     * @param workCode the value for ED_USER_WORK.WORK_CODE
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_USER_WORK.CREATE_TIME
     *
     * @return the value of ED_USER_WORK.CREATE_TIME
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_USER_WORK.CREATE_TIME
     *
     * @param createTime the value for ED_USER_WORK.CREATE_TIME
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_USER_WORK.STATUS
     *
     * @return the value of ED_USER_WORK.STATUS
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_USER_WORK.STATUS
     *
     * @param status the value for ED_USER_WORK.STATUS
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_USER_WORK.STATUS_NAME
     *
     * @return the value of ED_USER_WORK.STATUS_NAME
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public String getStatusName() {
        return statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_USER_WORK.STATUS_NAME
     *
     * @param statusName the value for ED_USER_WORK.STATUS_NAME
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public void setStatusName(String statusName) {
        this.statusName = statusName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_USER_WORK.READ_STATUS
     *
     * @return the value of ED_USER_WORK.READ_STATUS
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public String getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_USER_WORK.READ_STATUS
     *
     * @param readStatus the value for ED_USER_WORK.READ_STATUS
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    public void setReadStatus(String readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userWorkNo=").append(userWorkNo);
        sb.append(", userId=").append(userId);
        sb.append(", workCode=").append(workCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", statusName=").append(statusName);
        sb.append(", readStatus=").append(readStatus);
        sb.append("]");
        return sb.toString();
    }
}