package com.asiainfo.aigov.dao.edot.news;

import com.asiainfo.aigov.model.edot.news.UserNewsCat;
import com.asiainfo.aigov.model.edot.news.UserNewsCatExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserNewsCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int countByExample(UserNewsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int deleteByExample(UserNewsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int deleteByPrimaryKey(String userCatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int insert(UserNewsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int insertSelective(UserNewsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    List<UserNewsCat> selectByExampleWithRowbounds(UserNewsCatExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    List<UserNewsCat> selectByExample(UserNewsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    UserNewsCat selectByPrimaryKey(String userCatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int updateByExampleSelective(@Param("record") UserNewsCat record, @Param("example") UserNewsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int updateByExample(@Param("record") UserNewsCat record, @Param("example") UserNewsCatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int updateByPrimaryKeySelective(UserNewsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_NEWS_CAT
     *
     * @mbggenerated Tue Jun 28 11:46:13 CST 2016
     */
    int updateByPrimaryKey(UserNewsCat record);
}