package com.asiainfo.aigov.dao.healthcare.patients;

import com.asiainfo.aigov.model.healthcare.patients.PublicPatients;
import com.asiainfo.aigov.model.healthcare.patients.PublicPatientsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicPatientsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int countByExample(PublicPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int deleteByExample(PublicPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int deleteByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int insert(PublicPatients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int insertSelective(PublicPatients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    List<PublicPatients> selectByExampleWithRowbounds(PublicPatientsExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    List<PublicPatients> selectByExample(PublicPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    PublicPatients selectByPrimaryKey(String patientId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicPatients record, @Param("example") PublicPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int updateByExample(@Param("record") PublicPatients record, @Param("example") PublicPatientsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int updateByPrimaryKeySelective(PublicPatients record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_PATIENTS
     *
     * @mbggenerated Fri Apr 21 16:04:36 CST 2017
     */
    int updateByPrimaryKey(PublicPatients record);
}