package com.asiainfo.aigov.model.healthcare.doctor;

import java.math.BigDecimal;
import java.util.Date;

public class PublicBlacklist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.PATIENT_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private BigDecimal patientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.MISS_TYPE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String missType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.SOURCE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.HOSPITAL_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private BigDecimal hospitalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.BLACKLIST_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String blacklistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.NAME
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.ID_NO
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.CARD_NO
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.BLACK_DATE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private Date blackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.STATUS
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.UNBLACK_DATE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private Date unblackDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.CREATE_TIME
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.MISS_COUNT
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private Integer missCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.FIRST_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String firstOrderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.SECOND_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String secondOrderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.THRID_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String thridOrderid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.BAK1
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String bak1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.BAK2
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String bak2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.BAK3
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String bak3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC_BLACKLIST.BAK4
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    private String bak4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.ID
     *
     * @return the value of PUBLIC_BLACKLIST.ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.ID
     *
     * @param id the value for PUBLIC_BLACKLIST.ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.PATIENT_ID
     *
     * @return the value of PUBLIC_BLACKLIST.PATIENT_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public BigDecimal getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.PATIENT_ID
     *
     * @param patientId the value for PUBLIC_BLACKLIST.PATIENT_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setPatientId(BigDecimal patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.MISS_TYPE
     *
     * @return the value of PUBLIC_BLACKLIST.MISS_TYPE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getMissType() {
        return missType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.MISS_TYPE
     *
     * @param missType the value for PUBLIC_BLACKLIST.MISS_TYPE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setMissType(String missType) {
        this.missType = missType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.SOURCE
     *
     * @return the value of PUBLIC_BLACKLIST.SOURCE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.SOURCE
     *
     * @param source the value for PUBLIC_BLACKLIST.SOURCE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.HOSPITAL_ID
     *
     * @return the value of PUBLIC_BLACKLIST.HOSPITAL_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public BigDecimal getHospitalId() {
        return hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.HOSPITAL_ID
     *
     * @param hospitalId the value for PUBLIC_BLACKLIST.HOSPITAL_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setHospitalId(BigDecimal hospitalId) {
        this.hospitalId = hospitalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.BLACKLIST_ID
     *
     * @return the value of PUBLIC_BLACKLIST.BLACKLIST_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getBlacklistId() {
        return blacklistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.BLACKLIST_ID
     *
     * @param blacklistId the value for PUBLIC_BLACKLIST.BLACKLIST_ID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setBlacklistId(String blacklistId) {
        this.blacklistId = blacklistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.NAME
     *
     * @return the value of PUBLIC_BLACKLIST.NAME
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.NAME
     *
     * @param name the value for PUBLIC_BLACKLIST.NAME
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.ID_NO
     *
     * @return the value of PUBLIC_BLACKLIST.ID_NO
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.ID_NO
     *
     * @param idNo the value for PUBLIC_BLACKLIST.ID_NO
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.CARD_NO
     *
     * @return the value of PUBLIC_BLACKLIST.CARD_NO
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.CARD_NO
     *
     * @param cardNo the value for PUBLIC_BLACKLIST.CARD_NO
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.BLACK_DATE
     *
     * @return the value of PUBLIC_BLACKLIST.BLACK_DATE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public Date getBlackDate() {
        return blackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.BLACK_DATE
     *
     * @param blackDate the value for PUBLIC_BLACKLIST.BLACK_DATE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setBlackDate(Date blackDate) {
        this.blackDate = blackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.STATUS
     *
     * @return the value of PUBLIC_BLACKLIST.STATUS
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.STATUS
     *
     * @param status the value for PUBLIC_BLACKLIST.STATUS
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.UNBLACK_DATE
     *
     * @return the value of PUBLIC_BLACKLIST.UNBLACK_DATE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public Date getUnblackDate() {
        return unblackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.UNBLACK_DATE
     *
     * @param unblackDate the value for PUBLIC_BLACKLIST.UNBLACK_DATE
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setUnblackDate(Date unblackDate) {
        this.unblackDate = unblackDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.CREATE_TIME
     *
     * @return the value of PUBLIC_BLACKLIST.CREATE_TIME
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.CREATE_TIME
     *
     * @param createTime the value for PUBLIC_BLACKLIST.CREATE_TIME
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.MISS_COUNT
     *
     * @return the value of PUBLIC_BLACKLIST.MISS_COUNT
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public Integer getMissCount() {
        return missCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.MISS_COUNT
     *
     * @param missCount the value for PUBLIC_BLACKLIST.MISS_COUNT
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setMissCount(Integer missCount) {
        this.missCount = missCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.FIRST_ORDERID
     *
     * @return the value of PUBLIC_BLACKLIST.FIRST_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getFirstOrderid() {
        return firstOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.FIRST_ORDERID
     *
     * @param firstOrderid the value for PUBLIC_BLACKLIST.FIRST_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setFirstOrderid(String firstOrderid) {
        this.firstOrderid = firstOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.SECOND_ORDERID
     *
     * @return the value of PUBLIC_BLACKLIST.SECOND_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getSecondOrderid() {
        return secondOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.SECOND_ORDERID
     *
     * @param secondOrderid the value for PUBLIC_BLACKLIST.SECOND_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setSecondOrderid(String secondOrderid) {
        this.secondOrderid = secondOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.THRID_ORDERID
     *
     * @return the value of PUBLIC_BLACKLIST.THRID_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getThridOrderid() {
        return thridOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.THRID_ORDERID
     *
     * @param thridOrderid the value for PUBLIC_BLACKLIST.THRID_ORDERID
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setThridOrderid(String thridOrderid) {
        this.thridOrderid = thridOrderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.BAK1
     *
     * @return the value of PUBLIC_BLACKLIST.BAK1
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getBak1() {
        return bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.BAK1
     *
     * @param bak1 the value for PUBLIC_BLACKLIST.BAK1
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setBak1(String bak1) {
        this.bak1 = bak1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.BAK2
     *
     * @return the value of PUBLIC_BLACKLIST.BAK2
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getBak2() {
        return bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.BAK2
     *
     * @param bak2 the value for PUBLIC_BLACKLIST.BAK2
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setBak2(String bak2) {
        this.bak2 = bak2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.BAK3
     *
     * @return the value of PUBLIC_BLACKLIST.BAK3
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getBak3() {
        return bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.BAK3
     *
     * @param bak3 the value for PUBLIC_BLACKLIST.BAK3
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setBak3(String bak3) {
        this.bak3 = bak3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC_BLACKLIST.BAK4
     *
     * @return the value of PUBLIC_BLACKLIST.BAK4
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public String getBak4() {
        return bak4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC_BLACKLIST.BAK4
     *
     * @param bak4 the value for PUBLIC_BLACKLIST.BAK4
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    public void setBak4(String bak4) {
        this.bak4 = bak4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_BLACKLIST
     *
     * @mbggenerated Thu May 25 16:45:43 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", patientId=").append(patientId);
        sb.append(", missType=").append(missType);
        sb.append(", source=").append(source);
        sb.append(", hospitalId=").append(hospitalId);
        sb.append(", blacklistId=").append(blacklistId);
        sb.append(", name=").append(name);
        sb.append(", idNo=").append(idNo);
        sb.append(", cardNo=").append(cardNo);
        sb.append(", blackDate=").append(blackDate);
        sb.append(", status=").append(status);
        sb.append(", unblackDate=").append(unblackDate);
        sb.append(", createTime=").append(createTime);
        sb.append(", missCount=").append(missCount);
        sb.append(", firstOrderid=").append(firstOrderid);
        sb.append(", secondOrderid=").append(secondOrderid);
        sb.append(", thridOrderid=").append(thridOrderid);
        sb.append(", bak1=").append(bak1);
        sb.append(", bak2=").append(bak2);
        sb.append(", bak3=").append(bak3);
        sb.append(", bak4=").append(bak4);
        sb.append("]");
        return sb.toString();
    }
}