package com.asiainfo.aigov.dao.edot.layout;

import com.asiainfo.aigov.model.edot.layout.PageItemCfg;
import com.asiainfo.aigov.model.edot.layout.PageItemCfgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PageItemCfgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    int countByExample(PageItemCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    int deleteByExample(PageItemCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    int insert(PageItemCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    int insertSelective(PageItemCfg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    List<PageItemCfg> selectByExampleWithRowbounds(PageItemCfgExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    List<PageItemCfg> selectByExample(PageItemCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") PageItemCfg record, @Param("example") PageItemCfgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    int updateByExample(@Param("record") PageItemCfg record, @Param("example") PageItemCfgExample example);
}