package com.asiainfo.aigov.dao.edot.lifeSVC;

import com.asiainfo.aigov.model.edot.lifeSVC.WebMember;
import com.asiainfo.aigov.model.edot.lifeSVC.WebMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WebMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int countByExample(WebMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int deleteByExample(WebMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int deleteByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int insert(WebMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int insertSelective(WebMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    List<WebMember> selectByExampleWithRowbounds(WebMemberExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    List<WebMember> selectByExample(WebMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    WebMember selectByPrimaryKey(Integer memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") WebMember record, @Param("example") WebMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int updateByExample(@Param("record") WebMember record, @Param("example") WebMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int updateByPrimaryKeySelective(WebMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_member
     *
     * @mbggenerated Thu Aug 25 13:02:32 CST 2016
     */
    int updateByPrimaryKey(WebMember record);
}