package com.asiainfo.aigov.dao.edot.lifeSVC;

import com.asiainfo.aigov.model.edot.lifeSVC.WebServiceItem;
import com.asiainfo.aigov.model.edot.lifeSVC.WebServiceItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WebServiceItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int countByExample(WebServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int deleteByExample(WebServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int deleteByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int insert(WebServiceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int insertSelective(WebServiceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    List<WebServiceItem> selectByExampleWithRowbounds(WebServiceItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    List<WebServiceItem> selectByExample(WebServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    WebServiceItem selectByPrimaryKey(Integer itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int updateByExampleSelective(@Param("record") WebServiceItem record, @Param("example") WebServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int updateByExample(@Param("record") WebServiceItem record, @Param("example") WebServiceItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int updateByPrimaryKeySelective(WebServiceItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_service_item
     *
     * @mbggenerated Thu Aug 25 13:04:08 CST 2016
     */
    int updateByPrimaryKey(WebServiceItem record);
}