package com.asiainfo.aigov.model.healthcare.guidance;

import java.math.BigDecimal;

public class ZwzdParty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZWZD_PARTY.PARTYID
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    private BigDecimal partyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ZWZD_PARTY.PARTYNAME
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    private String partyname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZWZD_PARTY.PARTYID
     *
     * @return the value of ZWZD_PARTY.PARTYID
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    public BigDecimal getPartyid() {
        return partyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZWZD_PARTY.PARTYID
     *
     * @param partyid the value for ZWZD_PARTY.PARTYID
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    public void setPartyid(BigDecimal partyid) {
        this.partyid = partyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ZWZD_PARTY.PARTYNAME
     *
     * @return the value of ZWZD_PARTY.PARTYNAME
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    public String getPartyname() {
        return partyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ZWZD_PARTY.PARTYNAME
     *
     * @param partyname the value for ZWZD_PARTY.PARTYNAME
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    public void setPartyname(String partyname) {
        this.partyname = partyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ZWZD_PARTY
     *
     * @mbggenerated Wed May 03 13:13:43 CST 2017
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", partyid=").append(partyid);
        sb.append(", partyname=").append(partyname);
        sb.append("]");
        return sb.toString();
    }
}