package com.asiainfo.aigov.model.edot.hotLine;

import java.util.Date;

public class HotMail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.HOT_MAIL_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String hotMailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.HOT_MAIL_TITLE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String hotMailTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.HOT_MAIL_CONTENT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String hotMailContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.MODEL_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String modelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.HOT_MAIL_AIM
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String hotMailAim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.HOT_MAIL_FEEDBACK
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String hotMailFeedback;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.HOT_MAIL_INFO
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String hotMailInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.CREATE_DATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.CREATE_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.HOT_MAIL_DEPT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String hotMailDept;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.IS_READ
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.REPLY_STATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String replyState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.STATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.REPLY_CONTENT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String replyContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.REPLYER_NAME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String replyerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.REPLYER_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String replyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.REPLY_TIME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private Date replyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.SQ_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String sqCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.QUERY_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String queryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.PHONE_NO
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.DEPT_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String deptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_HOT_MAIL.DEPT_NAME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    private String deptName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.HOT_MAIL_ID
     *
     * @return the value of ED_HOT_MAIL.HOT_MAIL_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getHotMailId() {
        return hotMailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.HOT_MAIL_ID
     *
     * @param hotMailId the value for ED_HOT_MAIL.HOT_MAIL_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setHotMailId(String hotMailId) {
        this.hotMailId = hotMailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.HOT_MAIL_TITLE
     *
     * @return the value of ED_HOT_MAIL.HOT_MAIL_TITLE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getHotMailTitle() {
        return hotMailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.HOT_MAIL_TITLE
     *
     * @param hotMailTitle the value for ED_HOT_MAIL.HOT_MAIL_TITLE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setHotMailTitle(String hotMailTitle) {
        this.hotMailTitle = hotMailTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.HOT_MAIL_CONTENT
     *
     * @return the value of ED_HOT_MAIL.HOT_MAIL_CONTENT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getHotMailContent() {
        return hotMailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.HOT_MAIL_CONTENT
     *
     * @param hotMailContent the value for ED_HOT_MAIL.HOT_MAIL_CONTENT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setHotMailContent(String hotMailContent) {
        this.hotMailContent = hotMailContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.MODEL_ID
     *
     * @return the value of ED_HOT_MAIL.MODEL_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.MODEL_ID
     *
     * @param modelId the value for ED_HOT_MAIL.MODEL_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setModelId(String modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.HOT_MAIL_AIM
     *
     * @return the value of ED_HOT_MAIL.HOT_MAIL_AIM
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getHotMailAim() {
        return hotMailAim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.HOT_MAIL_AIM
     *
     * @param hotMailAim the value for ED_HOT_MAIL.HOT_MAIL_AIM
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setHotMailAim(String hotMailAim) {
        this.hotMailAim = hotMailAim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.HOT_MAIL_FEEDBACK
     *
     * @return the value of ED_HOT_MAIL.HOT_MAIL_FEEDBACK
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getHotMailFeedback() {
        return hotMailFeedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.HOT_MAIL_FEEDBACK
     *
     * @param hotMailFeedback the value for ED_HOT_MAIL.HOT_MAIL_FEEDBACK
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setHotMailFeedback(String hotMailFeedback) {
        this.hotMailFeedback = hotMailFeedback;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.HOT_MAIL_INFO
     *
     * @return the value of ED_HOT_MAIL.HOT_MAIL_INFO
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getHotMailInfo() {
        return hotMailInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.HOT_MAIL_INFO
     *
     * @param hotMailInfo the value for ED_HOT_MAIL.HOT_MAIL_INFO
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setHotMailInfo(String hotMailInfo) {
        this.hotMailInfo = hotMailInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.CREATE_DATE
     *
     * @return the value of ED_HOT_MAIL.CREATE_DATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.CREATE_DATE
     *
     * @param createDate the value for ED_HOT_MAIL.CREATE_DATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.CREATE_ID
     *
     * @return the value of ED_HOT_MAIL.CREATE_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.CREATE_ID
     *
     * @param createId the value for ED_HOT_MAIL.CREATE_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setCreateId(String createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.HOT_MAIL_DEPT
     *
     * @return the value of ED_HOT_MAIL.HOT_MAIL_DEPT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getHotMailDept() {
        return hotMailDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.HOT_MAIL_DEPT
     *
     * @param hotMailDept the value for ED_HOT_MAIL.HOT_MAIL_DEPT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setHotMailDept(String hotMailDept) {
        this.hotMailDept = hotMailDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.IS_READ
     *
     * @return the value of ED_HOT_MAIL.IS_READ
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.IS_READ
     *
     * @param isRead the value for ED_HOT_MAIL.IS_READ
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setIsRead(String isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.REPLY_STATE
     *
     * @return the value of ED_HOT_MAIL.REPLY_STATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getReplyState() {
        return replyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.REPLY_STATE
     *
     * @param replyState the value for ED_HOT_MAIL.REPLY_STATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setReplyState(String replyState) {
        this.replyState = replyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.STATE
     *
     * @return the value of ED_HOT_MAIL.STATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.STATE
     *
     * @param state the value for ED_HOT_MAIL.STATE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.REPLY_CONTENT
     *
     * @return the value of ED_HOT_MAIL.REPLY_CONTENT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getReplyContent() {
        return replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.REPLY_CONTENT
     *
     * @param replyContent the value for ED_HOT_MAIL.REPLY_CONTENT
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setReplyContent(String replyContent) {
        this.replyContent = replyContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.REPLYER_NAME
     *
     * @return the value of ED_HOT_MAIL.REPLYER_NAME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getReplyerName() {
        return replyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.REPLYER_NAME
     *
     * @param replyerName the value for ED_HOT_MAIL.REPLYER_NAME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setReplyerName(String replyerName) {
        this.replyerName = replyerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.REPLYER_ID
     *
     * @return the value of ED_HOT_MAIL.REPLYER_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getReplyerId() {
        return replyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.REPLYER_ID
     *
     * @param replyerId the value for ED_HOT_MAIL.REPLYER_ID
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setReplyerId(String replyerId) {
        this.replyerId = replyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.REPLY_TIME
     *
     * @return the value of ED_HOT_MAIL.REPLY_TIME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public Date getReplyTime() {
        return replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.REPLY_TIME
     *
     * @param replyTime the value for ED_HOT_MAIL.REPLY_TIME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setReplyTime(Date replyTime) {
        this.replyTime = replyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.SQ_CODE
     *
     * @return the value of ED_HOT_MAIL.SQ_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getSqCode() {
        return sqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.SQ_CODE
     *
     * @param sqCode the value for ED_HOT_MAIL.SQ_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setSqCode(String sqCode) {
        this.sqCode = sqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.QUERY_CODE
     *
     * @return the value of ED_HOT_MAIL.QUERY_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getQueryCode() {
        return queryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.QUERY_CODE
     *
     * @param queryCode the value for ED_HOT_MAIL.QUERY_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setQueryCode(String queryCode) {
        this.queryCode = queryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.PHONE_NO
     *
     * @return the value of ED_HOT_MAIL.PHONE_NO
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.PHONE_NO
     *
     * @param phoneNo the value for ED_HOT_MAIL.PHONE_NO
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.DEPT_CODE
     *
     * @return the value of ED_HOT_MAIL.DEPT_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getDeptCode() {
        return deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.DEPT_CODE
     *
     * @param deptCode the value for ED_HOT_MAIL.DEPT_CODE
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setDeptCode(String deptCode) {
        this.deptCode = deptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_HOT_MAIL.DEPT_NAME
     *
     * @return the value of ED_HOT_MAIL.DEPT_NAME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_HOT_MAIL.DEPT_NAME
     *
     * @param deptName the value for ED_HOT_MAIL.DEPT_NAME
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HOT_MAIL
     *
     * @mbggenerated Tue Jul 19 14:07:16 GMT+08:00 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hotMailId=").append(hotMailId);
        sb.append(", hotMailTitle=").append(hotMailTitle);
        sb.append(", hotMailContent=").append(hotMailContent);
        sb.append(", modelId=").append(modelId);
        sb.append(", hotMailAim=").append(hotMailAim);
        sb.append(", hotMailFeedback=").append(hotMailFeedback);
        sb.append(", hotMailInfo=").append(hotMailInfo);
        sb.append(", createDate=").append(createDate);
        sb.append(", createId=").append(createId);
        sb.append(", hotMailDept=").append(hotMailDept);
        sb.append(", isRead=").append(isRead);
        sb.append(", replyState=").append(replyState);
        sb.append(", state=").append(state);
        sb.append(", replyContent=").append(replyContent);
        sb.append(", replyerName=").append(replyerName);
        sb.append(", replyerId=").append(replyerId);
        sb.append(", replyTime=").append(replyTime);
        sb.append(", sqCode=").append(sqCode);
        sb.append(", queryCode=").append(queryCode);
        sb.append(", phoneNo=").append(phoneNo);
        sb.append(", deptCode=").append(deptCode);
        sb.append(", deptName=").append(deptName);
        sb.append("]");
        return sb.toString();
    }
}