package com.asiainfo.aigov.dao.edot.tklogin;

import com.asiainfo.aigov.model.edot.tklogin.LoginToken;
import com.asiainfo.aigov.model.edot.tklogin.LoginTokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

/** 
 * @Title        LoginTokenMapper.java
 * @Description: 用户登录的持久化层
 * @author:      Administrator
 * @date:        2017年8月3日下午4:28:47 
 *  
 */
public interface LoginTokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    int countByExample(LoginTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    int deleteByExample(LoginTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    int insert(LoginToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    int insertSelective(LoginToken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    List<LoginToken> selectByExampleWithRowbounds(LoginTokenExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    List<LoginToken> selectByExample(LoginTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    int updateByExampleSelective(@Param("record") LoginToken record, @Param("example") LoginTokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_LOGIN_TOKEN
     *
     * @mbggenerated Sat Jul 02 12:30:34 CST 2016
     */
    int updateByExample(@Param("record") LoginToken record, @Param("example") LoginTokenExample example);
}