package com.asiainfo.aigov.model.edot.layout;

public class PageItemCfg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.WORK_CODE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String workCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ITEM_ID
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ITEM_LABEL
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String itemLabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ITEM_LABEL_PROPERTY
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String itemLabelProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ITEM_VALUE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String itemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ITEM_VALUE_PROPERTY
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String itemValueProperty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ITEM_DESC
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String itemDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ITEM_TYPE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String itemType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.VALUE_MODE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String valueMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.REGION_NAME
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private String regionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ED_PAGE_ITEM_CFG.ORDER_NO
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    private Short orderNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.WORK_CODE
     *
     * @return the value of ED_PAGE_ITEM_CFG.WORK_CODE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getWorkCode() {
        return workCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.WORK_CODE
     *
     * @param workCode the value for ED_PAGE_ITEM_CFG.WORK_CODE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setWorkCode(String workCode) {
        this.workCode = workCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ITEM_ID
     *
     * @return the value of ED_PAGE_ITEM_CFG.ITEM_ID
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ITEM_ID
     *
     * @param itemId the value for ED_PAGE_ITEM_CFG.ITEM_ID
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ITEM_LABEL
     *
     * @return the value of ED_PAGE_ITEM_CFG.ITEM_LABEL
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getItemLabel() {
        return itemLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ITEM_LABEL
     *
     * @param itemLabel the value for ED_PAGE_ITEM_CFG.ITEM_LABEL
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setItemLabel(String itemLabel) {
        this.itemLabel = itemLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ITEM_LABEL_PROPERTY
     *
     * @return the value of ED_PAGE_ITEM_CFG.ITEM_LABEL_PROPERTY
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getItemLabelProperty() {
        return itemLabelProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ITEM_LABEL_PROPERTY
     *
     * @param itemLabelProperty the value for ED_PAGE_ITEM_CFG.ITEM_LABEL_PROPERTY
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setItemLabelProperty(String itemLabelProperty) {
        this.itemLabelProperty = itemLabelProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ITEM_VALUE
     *
     * @return the value of ED_PAGE_ITEM_CFG.ITEM_VALUE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ITEM_VALUE
     *
     * @param itemValue the value for ED_PAGE_ITEM_CFG.ITEM_VALUE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ITEM_VALUE_PROPERTY
     *
     * @return the value of ED_PAGE_ITEM_CFG.ITEM_VALUE_PROPERTY
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getItemValueProperty() {
        return itemValueProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ITEM_VALUE_PROPERTY
     *
     * @param itemValueProperty the value for ED_PAGE_ITEM_CFG.ITEM_VALUE_PROPERTY
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setItemValueProperty(String itemValueProperty) {
        this.itemValueProperty = itemValueProperty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ITEM_DESC
     *
     * @return the value of ED_PAGE_ITEM_CFG.ITEM_DESC
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getItemDesc() {
        return itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ITEM_DESC
     *
     * @param itemDesc the value for ED_PAGE_ITEM_CFG.ITEM_DESC
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ITEM_TYPE
     *
     * @return the value of ED_PAGE_ITEM_CFG.ITEM_TYPE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ITEM_TYPE
     *
     * @param itemType the value for ED_PAGE_ITEM_CFG.ITEM_TYPE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setItemType(String itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.VALUE_MODE
     *
     * @return the value of ED_PAGE_ITEM_CFG.VALUE_MODE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getValueMode() {
        return valueMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.VALUE_MODE
     *
     * @param valueMode the value for ED_PAGE_ITEM_CFG.VALUE_MODE
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setValueMode(String valueMode) {
        this.valueMode = valueMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.REGION_NAME
     *
     * @return the value of ED_PAGE_ITEM_CFG.REGION_NAME
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.REGION_NAME
     *
     * @param regionName the value for ED_PAGE_ITEM_CFG.REGION_NAME
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ED_PAGE_ITEM_CFG.ORDER_NO
     *
     * @return the value of ED_PAGE_ITEM_CFG.ORDER_NO
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public Short getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ED_PAGE_ITEM_CFG.ORDER_NO
     *
     * @param orderNo the value for ED_PAGE_ITEM_CFG.ORDER_NO
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    public void setOrderNo(Short orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_PAGE_ITEM_CFG
     *
     * @mbggenerated Thu Jun 02 20:46:09 GMT+08:00 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", workCode=").append(workCode);
        sb.append(", itemId=").append(itemId);
        sb.append(", itemLabel=").append(itemLabel);
        sb.append(", itemLabelProperty=").append(itemLabelProperty);
        sb.append(", itemValue=").append(itemValue);
        sb.append(", itemValueProperty=").append(itemValueProperty);
        sb.append(", itemDesc=").append(itemDesc);
        sb.append(", itemType=").append(itemType);
        sb.append(", valueMode=").append(valueMode);
        sb.append(", regionName=").append(regionName);
        sb.append(", orderNo=").append(orderNo);
        sb.append("]");
        return sb.toString();
    }
}