package com.asiainfo.aigov.dao.edot.work;

import com.asiainfo.aigov.model.edot.work.Material;
import com.asiainfo.aigov.model.edot.work.MaterialExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface MaterialMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int countByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int deleteByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String mateno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int insert(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int insertSelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    List<Material> selectByExampleWithBLOBsWithRowbounds(MaterialExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    List<Material> selectByExampleWithBLOBs(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    List<Material> selectByExampleWithRowbounds(MaterialExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    List<Material> selectByExample(MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    Material selectByPrimaryKey(String mateno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") Material record, @Param("example") MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int updateByExampleWithBLOBs(@Param("record") Material record, @Param("example") MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int updateByExample(@Param("record") Material record, @Param("example") MaterialExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int updateByPrimaryKeyWithBLOBs(Material record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_MATERIAL
     *
     * @mbggenerated Tue Jul 12 11:37:22 GMT+08:00 2016
     */
    int updateByPrimaryKey(Material record);
}