package com.asiainfo.aigov.dao.edot.work;

import com.asiainfo.aigov.model.edot.work.UserWork;
import com.asiainfo.aigov.model.edot.work.UserWorkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface UserWorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int countByExample(UserWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int deleteByExample(UserWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String userWorkNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int insert(UserWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int insertSelective(UserWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    List<UserWork> selectByExampleWithRowbounds(UserWorkExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    List<UserWork> selectByExample(UserWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    UserWork selectByPrimaryKey(String userWorkNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") UserWork record, @Param("example") UserWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int updateByExample(@Param("record") UserWork record, @Param("example") UserWorkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(UserWork record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_USER_WORK
     *
     * @mbggenerated Wed Jun 01 19:10:55 GMT+08:00 2016
     */
    int updateByPrimaryKey(UserWork record);
}