package com.asiainfo.aigov.dao.edot.work;

import com.asiainfo.aigov.model.edot.work.WorkDept;
import com.asiainfo.aigov.model.edot.work.WorkDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface WorkDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int countByExample(WorkDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int deleteByExample(WorkDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String deptcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int insert(WorkDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int insertSelective(WorkDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    List<WorkDept> selectByExampleWithRowbounds(WorkDeptExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    List<WorkDept> selectByExample(WorkDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    WorkDept selectByPrimaryKey(String deptcode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") WorkDept record, @Param("example") WorkDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int updateByExample(@Param("record") WorkDept record, @Param("example") WorkDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(WorkDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_WORK_DEPT
     *
     * @mbggenerated Thu Jul 07 17:19:23 GMT+08:00 2016
     */
    int updateByPrimaryKey(WorkDept record);
}