  <!-- jQuery -->
  <script src="${ctx}/vendor/jquery/jquery.min.js"></script>

  <!-- Angular -->
  <script src="${ctx}/vendor/angular/angular.js"></script>  
  <script src="${ctx}/vendor/angular/angular-animate/angular-animate.js"></script>
  <script src="${ctx}/vendor/angular/angular-cookies/angular-cookies.js"></script>
  <script src="${ctx}/vendor/angular/angular-resource/angular-resource.js"></script>
  <script src="${ctx}/vendor/angular/angular-sanitize/angular-sanitize.js"></script>
  <script src="${ctx}/vendor/angular/angular-touch/angular-touch.js"></script>
  
  <!-- Vendor -->
  <script src="${ctx}/vendor/angular/angular-route.min.js"></script> 
  <script src="${ctx}/vendor/angular/ngstorage/ngStorage.js"></script>

  <!-- bootstrap -->
  <script src="${ctx}/vendor/angular/angular-bootstrap/ui-bootstrap-tpls.js"></script> 
  <script src="${ctx}/static/bootstrap/js/bootstrap.min.js"></script> 
    
  <!-- lazyload -->
  <script src="${ctx}/vendor/angular/oclazyload/ocLazyLoad.js"></script>
  
  <!-- translate -->
  <script src="${ctx}/vendor/angular/angular-translate/angular-translate.js"></script>
  <script src="${ctx}/vendor/angular/angular-translate/loader-static-files.js"></script>
  <script src="${ctx}/vendor/angular/angular-translate/storage-cookie.js"></script>
  <script src="${ctx}/vendor/angular/angular-translate/storage-local.js"></script>

  <!-- App -->
  <script src="${ctx}/js/app/app.js"></script>
  <script src="${ctx}/js/app/config.lazyload.js"></script>
  <script src="${ctx}/js/app/data-service.js"></script>
  <script src="${ctx}/js/app/grid-helpers.js"></script>
  <script src="${ctx}/js/app/common.js"></script> 
  <script src="${ctx}/js/app/ui-butterbar.js"></script>  
  <script src="${ctx}/js/services/ui-load.js"></script>
  <script src="${ctx}/js/filters/fromNow.js"></script>
  <script src="${ctx}/js/directives/setnganimate.js"></script>
  <script src="${ctx}/js/directives/ui-focus.js"></script>
  <script src="${ctx}/js/directives/ui-fullscreen.js"></script>
  <script src="${ctx}/js/directives/ui-jq.js"></script>
  <script src="${ctx}/js/directives/ui-module.js"></script>
  <script src="${ctx}/js/directives/ui-nav.js"></script>
  <script src="${ctx}/js/directives/ui-scroll.js"></script>
  <script src="${ctx}/js/directives/ui-shift.js"></script>
  <script src="${ctx}/js/directives/ui-toggleclass.js"></script>
  <script src="${ctx}/js/directives/ui-validate.js"></script>
  <script src="${ctx}/static/toastr.js"></script>
  <script src="${ctx}/js/controllers/bootstrap.js"></script>
  
  <!-- Lazy loading -->