package com.asiainfo.aigov.dao.edot.common;

import com.asiainfo.aigov.model.edot.common.EdHttpLog;
import com.asiainfo.aigov.model.edot.common.EdHttpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

/**
* @ClassName: EdHttpLogMapper
* @Description: TODO(这里用一句话描述这个类的作用)
* @author Administrator
* @date 2017年7月24日 下午3:56:08
* **
*/
public interface EdHttpLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int countByExample(EdHttpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int deleteByExample(EdHttpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int insert(EdHttpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int insertSelective(EdHttpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    List<EdHttpLog> selectByExampleWithBLOBsWithRowbounds(EdHttpLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    List<EdHttpLog> selectByExampleWithBLOBs(EdHttpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    List<EdHttpLog> selectByExampleWithRowbounds(EdHttpLogExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    List<EdHttpLog> selectByExample(EdHttpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    EdHttpLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int updateByExampleSelective(@Param("record") EdHttpLog record, @Param("example") EdHttpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") EdHttpLog record, @Param("example") EdHttpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int updateByExample(@Param("record") EdHttpLog record, @Param("example") EdHttpLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int updateByPrimaryKeySelective(EdHttpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(EdHttpLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ED_HTTP_LOG
     *
     * @mbggenerated Fri Jun 03 18:47:58 CST 2016
     */
    int updateByPrimaryKey(EdHttpLog record);
}