package com.asiainfo.aigov.dao.healthcare.schedule;

import com.asiainfo.aigov.model.healthcare.schedule.PublicDoctorSchedule;
import com.asiainfo.aigov.model.healthcare.schedule.PublicDoctorScheduleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface PublicDoctorScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int countByExample(PublicDoctorScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int deleteByExample(PublicDoctorScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int deleteByPrimaryKey(@Param("hospitalId") String hospitalId, @Param("scheduleId") String scheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int insert(PublicDoctorSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int insertSelective(PublicDoctorSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    List<PublicDoctorSchedule> selectByExampleWithRowbounds(PublicDoctorScheduleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    List<PublicDoctorSchedule> selectByExample(PublicDoctorScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    PublicDoctorSchedule selectByPrimaryKey(@Param("hospitalId") String hospitalId, @Param("scheduleId") String scheduleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int updateByExampleSelective(@Param("record") PublicDoctorSchedule record, @Param("example") PublicDoctorScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int updateByExample(@Param("record") PublicDoctorSchedule record, @Param("example") PublicDoctorScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int updateByPrimaryKeySelective(PublicDoctorSchedule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC_DOCTOR_SCHEDULE
     *
     * @mbggenerated Fri Apr 21 09:58:33 CST 2017
     */
    int updateByPrimaryKey(PublicDoctorSchedule record);
}